DROP TABLE IF EXISTS lesson;
CREATE TABLE lesson (
    id INTEGER PRIMARY KEY,
    vocab_id INTEGER UNIQUE,
    FOREIGN KEY (vocab_id) REFERENCES vocabulary (id) ON UPDATE CASCADE ON DELETE CASCADE
);
