DROP TABLE IF EXISTS lesson;
CREATE TABLE lesson (
    id INTEGER PRIMARY KEY NOT NULL,
    vocab_id INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (vocab_id) REFERENCES vocabulary (id) ON UPDATE CASCADE ON DELETE CASCADE
);
