BEGIN TRANSACTION;

INSERT INTO vocabulary (
    hsk_level,
    hans,
    hant,
    pinyin_input,
    pinyin_display,
    definition,
    secondary_definitions
)
VALUES
    (1, '一',         '一',         'yi1',             'yī',            'one',                      'once; a'),
    (1, '人',         '人',         'ren2',            'rén',           'person',                   'man; people'),
    (1, '了',         '了',         'le5',             'le',            'completed action marker',  'modal particle'),
    (1, '几',         '幾',         'ji3',             'jǐ',            'how many; several; a few', NULL),
    (1, '八',         '八',         'ba1',             'bā',            'eight',                    NULL),
    (1, '十',         '十',         'shi2',            'shí',           'ten',                      NULL),
    (1, '二',         '二',         'er4',             'èr',            'two',                      NULL),
    (1, '七',         '七',         'qi1',             'qī',            'seven',                    NULL),
    (1, '九',         '九',         'jiu3',            'jiǔ',           'nine',                     NULL),
    (1, '大',         '大',         'da4',             'dà',            'big',                      'large'),
    (1, '上',         '上',         'shang4',          'shàng',         'above',                    'up'),
    (1, '下',         '下',         'xia4',            'xià',           'down',                     'downwards; below; lower; later; to decline; to go down'),
    (1, '个',         '個',         'ge5',             'ge',            'general measure word',     NULL),
    (1, '小',         '小',         'xiao3',           'xiǎo',          'small',                    'tiny; few; young'),
    (1, '三',         '三',         'san1',            'sān',           'three',                    NULL),
    (1, '不',         '不',         'bu4',             'bù',            'no',                       'not'),
    (1, '开',         '開',         'kai1',            'kāi',           'to open',                  'to start; to operate'),
    (1, '太',         '太',         'tai4',            'tài',           'too much',                 'very; extremely; highest; greatest'),
    (1, '水',         '水',         'shui3',           'shuǐ',          'water',                    NULL),
    (1, '月',         '月',         'yue4',            'yuè',           'moon',                     'month'),
    (1, '少',         '少',         'shao3',           'shǎo',          'few',                      'less; little; to lack; to be missing'),
    (1, '书',         '書',         'shu1',            'shū',           'book',                     'letter; document'),
    (1, '本',         '本',         'ben3',            'běn',           'measure word for books',   NULL),
    (1, '五',         '五',         'wu3',             'wǔ',            'five',                     NULL),
    (1, '六',         '六',         'liu4',            'liù',           'six',                      NULL),
    (1, '他',         '他',         'ta1',             'tā',            'he',                       'him'),
    (1, '去',         '去',         'qu4',             'qù',            'to go',                    NULL),
    (1, '叫',         '叫',         'jiao4',           'jiào',          'to be called',             'to call; to shout; to ask; to order'),
    (1, '写',         '寫',         'xie3',            'xiě',           'to write',                 'to compose'),
    (1, '号',         '號',         'hao4',            'hào',           'number',                   'day of a month'),
    (1, '女儿',       '女兒',       'nv3er2',          'nǚér',          'daughter',                 NULL),
    (1, '儿子',       '兒子',       'er2zi5',          'érzi',          'son',                      NULL),
    (1, '四',         '四',         'si4',             'sì',            'four',                     NULL),
    (1, '她',         '她',         'ta1',             'tā',            'she',                      NULL),
    (1, '有',         '有',         'you3',            'yǒu',           'have',                     NULL),
    (1, '好',         '好',         'hao3',            'hǎo',           'good',                     NULL),
    (1, '在',         '在',         'zai4',            'zài',           'at; on; in',               'indicates an action in progress'),
    (1, '那',         '那',         'na4',             'nà',            'that',                     'then'),
    (1, '会',         '會',         'hui4',            'huì',           'know how to',              NULL),
    (1, '多',         '多',         'duo1',            'duō',           'many',                     NULL),
    (1, '回',         '回',         'hui2',            'huí',           'to return',                'to reply; to go back'),
    (1, '年',         '年',         'nian2',           'nián',          'year',                     NULL),
    (1, '吃',         '吃',         'chi1',            'chī',           'to eat',                   NULL),
    (1, '买',         '買',         'mai3',            'mǎi',           'to buy',                   NULL),
    (1, '字',         '字',         'zi4',             'zì',            'character',                'letter'),
    (1, '岁',         '歲',         'sui4',            'suì',           'years old',                'age'),
    (1, '我',         '我',         'wo3',             'wǒ',            'I; me',                    NULL),
    (1, '你',         '你',         'ni3',             'nǐ',            'you',                      NULL),
    (1, '吗',         '嗎',         'ma5',             'ma',            'question particle',        'yes/no question particle'),
    (1, '来',         '來',         'lai2',            'lái',           'to come',                  'to arrive; ever since; next'),
    (1, '这',         '這',         'zhe4',            'zhè',           'this',                     NULL),
    (1, '里',         '裡',         'li3',             'lǐ',            'inside',                   NULL),
    (1, '坐',         '坐',         'zuo4',            'zuò',           'to sit',                   NULL),
    (1, '住',         '住',         'zhu4',            'zhù',           'to live; to reside',       'to stop'),
    (1, '下午',       '下午',       'xia4wu3',         'xiàwǔ',         'afternoon',                NULL),
    (1, '块',         '塊',         'kuai4',           'kuài',          'sum of money',             'yuan; dollar; lump; piece'),
    (1, '上午',       '上午',       'shang4wu3',       'shàngwǔ',       'morning',                  NULL),
    (1, '冷',         '冷',         'leng3',           'lěng',          'cold',                     NULL),
    (1, '的',         '的',         'de5',             'de',            'possessive particle',      NULL),
    (1, '和',         '和',         'he2',             'hé',            'and',                      'with'),
    (1, '说',         '說',         'shuo1',           'shuō',          'to speak',                 'to say; to talk'),
    (1, '呢',         '呢',         'ne5',             'ne',            'question particle',        'how about'),
    (1, '些',         '些',         'xie1',            'xiē',           'some',                     'few; several'),
    (1, '听',         '聽',         'ting1',           'tīng',          'to listen',                'to hear'),
    (1, '谁',         '誰',         'shei2',           'shéi',          'who',                      NULL),
    (1, '今天',       '今天',       'jin1tian1',       'jīntiān',       'today',                    NULL),
    (1, '钱',         '錢',         'qian2',           'qián',          'money',                    'coin'),
    (1, '天气',       '天氣',       'tian1qi4',        'tiānqì',        'weather',                  NULL),
    (1, '中午',       '中午',       'zhong1wu3',       'zhōngwǔ',       'noon',                     'midday'),
    (1, '狗',         '狗',         'gou3',            'gǒu',           'dog',                      NULL),
    (1, '是',         '是',         'shi4',            'shì',           'to be',                    'is; are; am'),
    (1, '很',         '很',         'hen3',            'hěn',           'very',                     'quite'),
    (1, '看',         '看',         'kan4',            'kàn',           'to look at',               'to see; to watch'),
    (1, '哪',         '哪',         'na3',             'nǎ',            'which',                    'how'),
    (1, '点',         '點',         'dian3',           'diǎn',          'o''clock',                 'a dot; a little'),
    (1, '茶',         '茶',         'cha2',            'chá',           'tea',                      NULL),
    (1, '飞机',       '飛機',       'fei1ji1',         'fēijī',         'airplane',                 NULL),
    (1, '都',         '都',         'dou1',            'dōu',           'all',                      'both'),
    (1, '能',         '能',         'neng2',           'néng',          'can',                      'to be able'),
    (1, '家',         '家',         'jia1',            'jiā',           'home',                     'family'),
    (1, '请',         '請',         'qing3',           'qǐng',          'please',                   'to invite; to treat someone to something'),
    (1, '工作',       '工作',       'gong1zuo4',       'gōngzuò',       'work',                     'a job'),
    (1, '多少',       '多少',       'duo1shao5',       'duōshao',       'how much; how many',       NULL),
    (1, '再见',       '再見',       'zai4jian4',       'zàijiàn',       'goodbye',                  'see you later'),
    (1, '读',         '讀',         'du2',             'dú',            'to read',                  'to study'),
    (1, '爱',         '愛',         'ai4',             'ài',            'love',                     NULL),
    (1, '热',         '熱',         're4',             'rè',            'hot',                      'heat'),
    (1, '什么',       '什麼',       'shen2me5',        'shénme',        'what',                     NULL),
    (1, '做',         '做',         'zuo4',            'zuò',           'to do',                    'to make'),
    (1, '哪儿',       '哪兒',       'na3r5',           'nǎr',           'where',                    NULL),
    (1, '学习',       '學習',       'xue2xi2',         'xuéxí',         'to study',                 'to learn'),
    (1, '东西',       '東西',       'dong1xi5',        'dōngxi',        'things',                   'stuff'),
    (1, '认识',       '認識',       'ren4shi5',        'rènshi',        'to know',                  'to know a person; to recognize'),
    (1, '先生',       '先生',       'xian1sheng5',     'xiānsheng',     'Mr.',                      'Sir'),
    (1, '小姐',       '小姐',       'xiao3jie5',       'xiǎojie',       'Miss',                     'young lady; Ms.'),
    (1, '下雨',       '下雨',       'xia4yu3',         'xiàyǔ',         'to rain',                  NULL),
    (1, '菜',         '菜',         'cai4',            'cài',           'dish',                     'type of food; vegetables'),
    (1, '猫',         '貓',         'mao1',            'māo',           'cat',                      NULL),
    (1, '杯子',       '杯子',       'bei1zi5',         'bēizi',         'cup',                      'glass'),
    (1, '我们',       '我們',       'wo3men5',         'wǒmen',         'we',                       'us'),
    (1, '怎么',       '怎麼',       'zen3me5',         'zěnme',         'how',                      NULL),
    (1, '一点儿',     '一點兒',     'yi4dian3r5',      'yìdiǎnr',       'a bit',                    'a few'),
    (1, '喝',         '喝',         'he1',             'hē',            'to drink',                 NULL),
    (1, '妈妈',       '媽媽',       'ma1ma5',          'māma',          'mom',                      'mum'),
    (1, '明天',       '明天',       'ming2tian1',      'míngtiān',      'tomorrow',                 NULL),
    (1, '朋友',       '朋友',       'peng2you5',       'péngyou',       'friend',                   NULL),
    (1, '老师',       '老師',       'lao3shi1',        'lǎoshī',        'teacher',                  NULL),
    (1, '名字',       '名字',       'ming2zi5',        'míngzi',        'name',                     NULL),
    (1, '医生',       '醫生',       'yi1sheng1',       'yīshēng',       'doctor',                   NULL),
    (1, '分钟',       '分鐘',       'fen1zhong1',      'fēnzhōng',      'minute',                   'measure word for time'),
    (1, '水果',       '水果',       'shui3guo3',       'shuǐguǒ',       'fruit',                    NULL),
    (1, '中国',       '中國',       'Zhong1guo2',      'Zhōngguó',      'China',                    NULL),
    (1, '喂',         '喂',         'wei4',            'wèi',           'hello',                    'hello on the phone'),
    (1, '没有',       '沒有',       'mei2you3',        'méiyǒu',        'to not have',              'there is not'),
    (1, '想',         '想',         'xiang3',          'xiǎng',         'to want',                  'to think; to believe; to suppose'),
    (1, '看见',       '看見',       'kan4jian4',       'kànjiàn',       'to see',                   'to catch sight of'),
    (1, '学生',       '學生',       'xue2sheng5',      'xuésheng',      'student',                  NULL),
    (1, '昨天',       '昨天',       'zuo2tian1',       'zuótiān',       'yesterday',                NULL),
    (1, '电视',       '電視',       'dian4shi4',       'diànshì',       'television',               'TV'),
    (1, '米饭',       '米飯',       'mi3fan4',         'mǐfàn',         'rice',                     'cooked rice'),
    (1, '桌子',       '桌子',       'zhuo1zi5',        'zhuōzi',        'table',                    'desk'),
    (1, '北京',       '北京',       'Bei3jing1',       'Běijīng',       'Beijing',                  NULL),
    (1, '现在',       '現在',       'xian4zai4',       'xiànzài',       'now',                      NULL),
    (1, '同学',       '同學',       'tong2xue2',       'tóngxué',       'classmate',                'fellow student; schoolmate'),
    (1, '衣服',       '衣服',       'yi1fu5',          'yīfu',          'clothes',                  NULL),
    (1, '汉语',       '漢語',       'Han4yu3',         'Hànyǔ',         'Chinese language',         NULL),
    (1, '后面',       '后面',       'hou4mian5',       'hòumian',       'behind',                   'back'),
    (1, '饭店',       '飯店',       'fan4dian4',       'fàndiàn',       'restaurant',               'hotel'),
    (1, '电脑',       '電腦',       'dian4nao3',       'diànnǎo',       'computer',                 NULL),
    (1, '椅子',       '椅子',       'yi3zi5',          'yǐzi',          'chair',                    NULL),
    (1, '高兴',       '高興',       'gao1xing4',       'gāoxìng',       'happy',                    'glad'),
    (1, '医院',       '醫院',       'yi1yuan4',        'yīyuàn',        'hospital',                 NULL),
    (1, '苹果',       '蘋果',       'ping2guo3',       'píngguǒ',       'apple',                    NULL),
    (1, '时候',       '時候',       'shi2hou5',        'shíhou',        'time',                     'moment; period'),
    (1, '不客气',     '不客氣',     'bu2 ke4qi5',      'bú kèqi',       'you''re welcome',          'don''t be polite'),
    (1, '喜欢',       '喜歡',       'xi3huan5',        'xǐhuan',        'to like',                  NULL),
    (1, '前面',       '前面',       'qian2mian4',      'qiánmiàn',      'in front',                 'ahead'),
    (1, '学校',       '學校',       'xue2xiao4',       'xuéxiào',       'school',                   NULL),
    (1, '打电话',     '打電話',     'da3 dian4hua4',   'dǎ diànhuà',    'to make a phone call',     NULL),
    (1, '对不起',     '對不起',     'dui4bu5qi3',      'duìbuqǐ',       'sorry',                    'I beg your pardon'),
    (1, '商店',       '商店',       'shang1dian4',     'shāngdiàn',     'shop',                     'store'),
    (1, '出租车',     '出租車',     'chu1zu1che1',     'chūzūchē',      'taxi',                     'cab'),
    (1, '没关系',     '沒關系',     'mei2 guan1xi5',   'méi guānxi',    'it doesn''t matter',       'never mind'),
    (1, '电影',       '電影',       'dian4ying3',      'diànyǐng',      'movie',                    'film'),
    (1, '星期',       '星期',       'xing1qi1',        'xīngqī',        'week',                     NULL),
    (1, '睡觉',       '睡覺',       'shui4 jiao4',     'shuì jiào',     'to sleep',                 'to go to bed'),
    (1, '漂亮',       '漂亮',       'piao4liang5',     'piàoliang',     'pretty',                   'beautiful'),
    (1, '怎么样',     '怎麼樣',     'zen3me5yang4',    'zěnmeyàng',     'how about',                'how is it; how was it'),
    (1, '谢谢',       '謝謝',       'xie4xie5',        'xièxie',        'thank you',                NULL),
    (1, '爸爸',       '爸爸',       'ba4ba5',          'bàba',          'dad',                      NULL)
;

COMMIT TRANSACTION;
