BEGIN TRANSACTION;

INSERT INTO vocabulary (
    hsk_level,
    hans,
    hant,
    pinyin_input,
    pinyin_display,
    definition
)
VALUES
    (1, '一',         '一',         'yi1',             'yī',            'one; once; a'),
    (1, '人',         '人',         'ren2',            'rén',           'person; man; people'),
    (1, '了',         '了',         'le5',             'le',            'indicates a completed or finished action'),
    (1, '几',         '幾',         'ji3',             'jǐ',            'how many; several; a few'),
    (1, '八',         '八',         'ba1',             'bā',            'eight'),
    (1, '十',         '十',         'shi2',            'shí',           'ten'),
    (1, '二',         '二',         'er4',             'èr',            'two'),
    (1, '七',         '七',         'qi1',             'qī',            'seven'),
    (1, '九',         '九',         'jiu3',            'jiǔ',           'nine'),
    (1, '大',         '大',         'da4',             'dà',            'big; large'),
    (1, '上',         '上',         'shang4',          'shàng',         'above; up'),
    (1, '下',         '下',         'xia4',            'xià',           'fall; below'),
    (1, '个',         '個',         'ge5',             'ge',            'general measure word'),
    (1, '小',         '小',         'xiao3',           'xiǎo',          'small; young'),
    (1, '三',         '三',         'san1',            'sān',           'three'),
    (1, '不',         '不',         'bu4',             'bù',            'no; not'),
    (1, '开',         '開',         'kai1',            'kāi',           'to open; to start; to operate (a vehicle)'),
    (1, '太',         '太',         'tai4',            'tài',           'too (much)'),
    (1, '水',         '水',         'shui3',           'shuǐ',          'water'),
    (1, '月',         '月',         'yue4',            'yuè',           'moon; month'),
    (1, '少',         '少',         'shao3',           'shǎo',          'few; little'),
    (1, '书',         '書',         'shu1',            'shū',           'book; letter'),
    (1, '本',         '本',         'ben3',            'běn',           'measure word for books'),
    (1, '五',         '五',         'wu3',             'wǔ',            'five'),
    (1, '六',         '六',         'liu4',            'liù',           'six'),
    (1, '他',         '他',         'ta1',             'tā',            'he; him'),
    (1, '去',         '去',         'qu4',             'qù',            'go; to leave'),
    (1, '叫',         '叫',         'jiao4',           'jiào',          'to be called'),
    (1, '写',         '寫',         'xie3',            'xiě',           'to write; to compose'),
    (1, '号',         '號',         'hao4',            'hào',           'number; day of a month'),
    (1, '女儿',       '女兒',       'nv3er2',          'nǚér',          'daughter'),
    (1, '儿子',       '兒子',       'er2zi5',          'érzi',          'son'),
    (1, '四',         '四',         'si4',             'sì',            'four'),
    (1, '她',         '她',         'ta1',             'tā',            'she'),
    (1, '有',         '有',         'you3',            'yǒu',           'have'),
    (1, '好',         '好',         'hao3',            'hǎo',           'good'),
    (1, '在',         '在',         'zai4',            'zài',           'at; on; in; indicates an action in progress'),
    (1, '那',         '那',         'na4',             'nà',            'that; then'),
    (1, '会',         '會',         'hui4',            'huì',           'know how to'),
    (1, '多',         '多',         'duo1',            'duō',           'many'),
    (1, '回',         '回',         'hui2',            'huí',           'to return; to reply; to go back'),
    (1, '年',         '年',         'nian2',           'nián',          'year'),
    (1, '吃',         '吃',         'chi1',            'chī',           'eat'),
    (1, '买',         '買',         'mai3',            'mǎi',           'to buy'),
    (1, '字',         '字',         'zi4',             'zì',            'letter; character'),
    (1, '岁',         '歲',         'sui4',            'suì',           'years old; age'),
    (1, '我',         '我',         'wo3',             'wǒ',            'I; me'),
    (1, '你',         '你',         'ni3',             'nǐ',            'you (singular)'),
    (1, '吗',         '嗎',         'ma5',             'ma',            'indicates a yes/no question (added to a statement)'),
    (1, '来',         '來',         'lai2',            'lái',           'come; arrive; ever since; next'),
    (1, '这',         '這',         'zhe4',            'zhè',           'this'),
    (1, '里',         '裡',         'li3',             'lǐ',            'inside; Chinese mile (~.5 km)'),
    (1, '坐',         '坐',         'zuo4',            'zuò',           'sit'),
    (1, '住',         '住',         'zhu4',            'zhù',           'to live; reside; to stop'),
    (1, '下午',       '下午',       'xia4wu3',         'xiàwǔ',         'afternoon'),
    (1, '块',         '塊',         'kuai4',           'kuài',          'lump; piece; sum of money'),
    (1, '上午',       '上午',       'shang4wu3',       'shàngwǔ',       'late morning (before noon)'),
    (1, '冷',         '冷',         'leng3',           'lěng',          'cold'),
    (1, '的',         '的',         'de5',             'de',            'indicates possession, like adding ''s to a noun'),
    (1, '和',         '和',         'he2',             'hé',            'and; with'),
    (1, '说',         '說',         'shuo1',           'shuō',          'speak'),
    (1, '呢',         '呢',         'ne5',             'ne',            'indicates a question; how about...?;'),
    (1, '些',         '些',         'xie1',            'xiē',           'some; few; several'),
    (1, '听',         '聽',         'ting1',           'tīng',          'listen; hear'),
    (1, '谁',         '誰',         'shei2',           'shéi',          'who'),
    (1, '今天',       '今天',       'jin1tian1',       'jīntiān',       'today'),
    (1, '钱',         '錢',         'qian2',           'qián',          'money; coin'),
    (1, '天气',       '天氣',       'tian1qi4',        'tiānqì',        'weather'),
    (1, '中午',       '中午',       'zhong1wu3',       'zhōngwǔ',       'noon; midday'),
    (1, '狗',         '狗',         'gou3',            'gǒu',           'dog'),
    (1, '是',         '是',         'shi4',            'shì',           'be; is; are; am'),
    (1, '很',         '很',         'hen3',            'hěn',           'very; quite'),
    (1, '看',         '看',         'kan4',            'kàn',           'see; look at; to watch'),
    (1, '哪',         '哪',         'na3',             'nǎa',           'which; how'),
    (1, '点',         '點',         'dian3',           'diǎn',          'a dot; a little; o''clock'),
    (1, '茶',         '茶',         'cha2',            'chá',           'tea'),
    (1, '飞机',       '飛機',       'fei1ji1',         'fēijī',         'airplane'),
    (1, '都',         '都',         'dou1',            'dōu',           'all; both'),
    (1, '能',         '能',         'neng2',           'néng',          'can; be able'),
    (1, '家',         '家',         'jia1',            'jiā',           'family; home'),
    (1, '请',         '請',         'qing3',           'qǐng',          'please; invite; to treat someone to something'),
    (1, '工作',       '工作',       'gong1zuo4',       'gōngzuò',       'work; a job'),
    (1, '多少',       '多少',       'duo1shao5',       'duōshao',       'how much?; how many?'),
    (1, '再见',       '再見',       'zai4jian4',       'zàijiàn',       'goodbye; see you later'),
    (1, '读',         '讀',         'du2',             'dú',            'to read; to study'),
    (1, '爱',         '愛',         'ai4',             'ài',            'love'),
    (1, '热',         '熱',         're4',             'rè',            'heat; hot'),
    (1, '什么',       '什麼',       'shen2me5',        'shénme',        'what? (replaces the noun to turn a statement into a question)'),
    (1, '做',         '做',         'zuo4',            'zuò',           'do; make'),
    (1, '哪儿',       '哪兒',       'na3r5',           'nǎr',           'where? (Beijing accent)'),
    (1, '学习',       '學習',       'xue2xi2',         'xuéxí',         'learn; to study'),
    (1, '东西',       '東西',       'dong1xi5',        'dōngxi',        'things; stuff'),
    (1, '认识',       '認識',       'ren4shi5',        'rènshi',        'recognize; know (a person)'),
    (1, '先生',       '先生',       'xian1sheng5',     'xiānsheng',     'Mr.; Sir'),
    (1, '小姐',       '小姐',       'xiao3jie5',       'xiǎojie',       'young lady; miss; Ms.'),
    (1, '下雨',       '下雨',       'xia4yu3',         'xiàyǔ',         'to rain'),
    (1, '菜',         '菜',         'cai4',            'cài',           'dish (type of food); vegetables'),
    (1, '猫',         '貓',         'mao1',            'māo',           'cat'),
    (1, '杯子',       '杯子',       'bei1zi5',         'bēizi',         'cup; glass'),
    (1, '我们',       '我們',       'wo3men5',         'wǒmen',         'we; us'),
    (1, '怎么',       '怎麼',       'zen3me5',         'zěnme',         'how?'),
    (1, '一点儿',     '一點兒',     'yi4dian3r5',      'yìdiǎnr',       'a bit; a few'),
    (1, '喝',         '喝',         'he1',             'hē',            'to drink'),
    (1, '妈妈',       '媽媽',       'ma1ma5',          'māma',          'mom; mum'),
    (1, '明天',       '明天',       'ming2tian1',      'míngtiān',      'tomorrow'),
    (1, '朋友',       '朋友',       'peng2you5',       'péngyou',       'friend'),
    (1, '老师',       '老師',       'lao3shi1',        'lǎoshī',        'teacher'),
    (1, '名字',       '名字',       'ming2zi5',        'míngzi',        'name'),
    (1, '医生',       '醫生',       'yi1sheng1',       'yīshēng',       'doctor'),
    (1, '分钟',       '分鐘',       'fen1zhong1',      'fēnzhōng',      'minute; (measure word for time)'),
    (1, '水果',       '水果',       'shui3guo3',       'shuǐguǒ',       'fruit'),
    (1, '中国',       '中國',       'Zhong1guo2',      'Zhōngguó',      'China'),
    (1, '喂',         '喂',         'wei4',            'wèi',           'hello (on the phone)'),
    (1, '没有',       '沒有',       'mei2you3',        'méiyǒu',        'not have; there is not'),
    (1, '想',         '想',         'xiang3',          'xiǎng',         'think; believe; suppose; would like to'),
    (1, '看见',       '看見',       'kan4jian4',       'kànjiàn',       'see; catch sight of'),
    (1, '学生',       '學生',       'xue2sheng5',      'xuésheng',      'student'),
    (1, '昨天',       '昨天',       'zuo2tian1',       'zuótiān',       'yesterday'),
    (1, '电视',       '電視',       'dian4shi4',       'diànshì',       'television; TV'),
    (1, '米饭',       '米飯',       'mi3fan4',         'mǐfàn',         '(cooked) rice'),
    (1, '桌子',       '桌子',       'zhuo1zi5',        'zhuōzi',        'table; desk'),
    (1, '北京',       '北京',       'Bei3jing1',       'Běijīng',       'Beijing'),
    (1, '现在',       '現在',       'xian4zai4',       'xiànzài',       'now'),
    (1, '同学',       '同學',       'tong2xue2',       'tóngxué',       'fellow student; schoolmate'),
    (1, '衣服',       '衣服',       'yi1fu5',          'yīfu',          'clothes'),
    (1, '汉语',       '漢語',       'Han4yu3',         'Hànyǔ',         'Chinese language'),
    (1, '后面',       '后面',       'hou4mian5',       'hòumian',       'back; behind'),
    (1, '饭店',       '飯店',       'fan4dian4',       'fàndiàn',       'restaurant; hotel'),
    (1, '电脑',       '電腦',       'dian4nao3',       'diànnǎo',       'computer'),
    (1, '椅子',       '椅子',       'yi3zi5',          'yǐzi',          'chair'),
    (1, '高兴',       '高興',       'gao1xing4',       'gāoxìng',       'happy; glad'),
    (1, '医院',       '醫院',       'yi1yuan4',        'yīyuàn',        'hospital'),
    (1, '苹果',       '蘋果',       'ping2guo3',       'píngguǒ',       'apple'),
    (1, '时候',       '時候',       'shi2hou5',        'shíhou',        'time'),
    (1, '不客气',     '不客氣',     'bu2 ke4qi5',      'bú kèqi',       'you''re welcome; don''t be polite'),
    (1, '喜欢',       '喜歡',       'xi3huan5',        'xǐhuan',        'to like'),
    (1, '前面',       '前面',       'qian2mian4',      'qiánmiàn',      'in front'),
    (1, '学校',       '學校',       'xue2xiao4',       'xuéxiào',       'school'),
    (1, '打电话',     '打電話',     'da3 dian4hua4',   'dǎ diànhuà',    'make a phone call'),
    (1, '对不起',     '對不起',     'dui4bu5qi3',      'duìbuqǐ',       'sorry'),
    (1, '商店',       '商店',       'shang1dian4',     'shāngdiàn',     'shop; store'),
    (1, '出租车',     '出租車',     'chu1zu1che1',     'chūzūchē',      'taxi; cab'),
    (1, '没关系',     '沒關系',     'mei2 guan1xi5',   'méi guānxi',    'it doesn''t matter; never mind'),
    (1, '电影',       '電影',       'dian4ying3',      'diànyǐng',      'movie; film'),
    (1, '星期',       '星期',       'xing1qi1',        'xīngqī',        'week'),
    (1, '睡觉',       '睡覺',       'shui4 jiao4',     'shuì jiào',     'to sleep; go to bed'),
    (1, '漂亮',       '漂亮',       'piao4liang5',     'piàoliang',     'pretty; beautiful'),
    (1, '怎么样',     '怎麼樣',     'zen3me5yang4',    'zěnmeyàng',     'how about?; how is/was it?'),
    (1, '谢谢',       '謝謝',       'xie4xie5',        'xièxie',        'thank you'),
    (1, '爸爸',       '爸爸',       'ba4ba5',          'bàba',          'Dad')
;

COMMIT TRANSACTION;
