BEGIN TRANSACTION;

INSERT INTO vocabulary (
    hsk_level,
    hans,
    hant,
    pinyin_input,
    pinyin_display,
    definition
)
VALUES
    (2, '吧',       '吧',       'ba5',                'ba',             'particle indicating polite suggestion; | onomatopoeia | bar (serving drinks, providing internet access, etc.)'),
    (2, '白',       '白',       'bai2',               'bái',            'white; snowy; pure; bright; empty (Kangxi radical 106)'),
    (2, '百',       '百',       'bai3',               'bǎi',            'hundred'),
    (2, '帮助',     '幫助',     'bang1zhu4',          'bāngzhù',        'help; assist; aid'),
    (2, '报纸',     '報紙',     'bao4zhi3',           'bàozhǐ',         'newspaper'),
    (2, '比',       '比',       'bi3',                'bǐ',             'compare; (indicates comparison) (Kangxi radical 81); to gesticulate as one talks'),
    (2, '别',       '別',       'bie2',               'bié',            'don''t do something; don''t | depart; | other; difference; distinguish'),
    (2, '宾馆',     '賓館',     'bin1guan3',          'bīnguǎn',        'guesthouse; hotel'),
    (2, '长',       '長',       'chang2,              zhang3',          'cháng, zhǎng', 'long; length | grow; chief (Kangxi radical 168)'),
    (2, '唱歌',     '唱歌',     'chang4ge1',          'chànggē',        'sing (a song)'),
    (2, '出',       '出',       'chu1',               'chū',            'go out; occur'),
    (2, '穿',       '穿',       'chuan1',             'chuān',          'to wear; put on; penetrate'),
    (2, '次',       '次',       'ci4',                'cì',             '(mw for number of times of occurrence); nth; order'),
    (2, '从',       '從',       'cong2',              'cóng',           'from; obey; observe'),
    (2, '错',       '錯',       'cuo4',               'cuò',            'mistake; error; blunder; miss an opportunity'),
    (2, '打篮球',   '打籃球',   'da3 lan2qiu2',       'dǎ lánqiú',      'play basketball'),
    (2, '大家',     '大家',     'da4jia1',            'dàjiā',          'everyone'),
    (2, '到',       '到',       'dao4',               'dào',            'arrive (at a place); until (a time)'),
    (2, '得',       '得',       'de5',                'de',             '(complement particle)'),
    (2, '等',       '等',       'deng3',              'děng',           'to wait; rank; equal; etc.'),
    (2, '弟弟',     '弟弟',     'di4di5',             'dìdi',           'younger brother'),
    (2, '第一',     '第一',     'di4yi1',             'dìyī',           'first; number 1'),
    (2, '懂',       '懂',       'dong3',              'dǒng',           'understand; know'),
    (2, '对',       '對',       'dui4',               'duì',            'correct; a pair; to face; be opposite; to; towards'),
    (2, '房间',     '房間',     'fang2jian1',         'fángjiān',       'room'),
    (2, '非常',     '非常',     'fei1chang2',         'fēicháng',       'extremely; extraordinary; very'),
    (2, '服务员',   '服務員',   'fu2wu4yuan2',        'fúwùyuán',       'waiter/waitress; server; attendant'),
    (2, '高',       '高',       'gao1',               'gāo',            'high; tall (Kangxi radical 189)'),
    (2, '告诉',     '告訴',     'gao4su5',            'gàosu',          'to tell; inform'),
    (2, '哥哥',     '哥哥',     'ge1ge5',             'gēge',           'older brother'),
    (2, '给',       '給',       'gei3',               'gěi',            'to give; to grant; (passive particle)'),
    (2, '公共汽车', '公共汽車', 'gong1gong4 qi4che1', 'gōnggòng qìchē', '(public) bus'),
    (2, '公司',     '公司',     'gong1si1',           'gōngsī',         'company; corporation'),
    (2, '贵',       '貴',       'gui4',               'guì',            'expensive; noble; honorable; Guizhou province (abbreviation)'),
    (2, '过',       '過',       'guo4',               'guò',            'to pass; to cross; go over; (indicates a past experience)'),
    (2, '还',       '還',       'hai2',               'hái',            'still; yet; in addition; even'),
    (2, '孩子',     '孩子',     'hai2zi5',            'háizi',          'child; children; son or daughter'),
    (2, '好吃',     '好吃',     'hao3chi1',           'hǎochī',         'tasty'),
    (2, '黑',       '黑',       'hei1',               'hēi',            'black; dark (Kangxi radical 203); Heilongjiang province (abbreviation)'),
    (2, '红',       '紅',       'hong2',              'hóng',           'red; symbol of success; bonus; popular'),
    (2, '火车站',   '火車站',   'huo3che1zhan4',      'huǒchēzhàn',     'train station'),
    (2, '机场',     '機場',     'ji1chang3',          'jīchǎng',        'airport; airfield'),
    (2, '鸡蛋',     '雞蛋',     'ji1dan4',            'jīdàn',          '(chicken) egg'),
    (2, '件',       '件',       'jian4',              'jiàn',           '(mw for things, clothes, and items)'),
    (2, '教室',     '教室',     'jiao4shi4',          'jiàoshì',        'classroom'),
    (2, '姐姐',     '姐姐',     'jie3jie5',           'jiějie',         'older sister'),
    (2, '介绍',     '介紹',     'jie4shao4',          'jièshào',        'to introduce; recommend; introduction'),
    (2, '进',       '進',       'jin4',               'jìn',            'enter; come in'),
    (2, '近',       '近',       'jin4',               'jìn',            'near; close (to)'),
    (2, '就',       '就',       'jiu4',               'jiù',            'then; at once; just; only; with regard to'),
    (2, '觉得',     '覺得',     'jue2de5',            'juéde',          'feel; think'),
    (2, '咖啡',     '咖啡',     'ka1fei1',            'kāfēi',          'coffee'),
    (2, '开始',     '開始',     'kai1shi3',           'kāishǐ',         'begin; to start; beginning'),
    (2, '考试',     '考試',     'kao3shi4',           'kǎoshì',         'test; exam; to give or take a test'),
    (2, '可能',     '可能',     'ke3neng2',           'kěnéng',         'possible; maybe'),
    (2, '可以',     '可以',     'ke3yi3',             'kěyǐ',           'can; may; possible; okay'),
    (2, '课',       '課',       'ke4',                'kè',             'class; subject; lesson; course'),
    (2, '快',       '快',       'kuai4',              'kuài',           'fast; quick; swift'),
    (2, '快乐',     '快樂',     'kuai4le4',           'kuàilè',         'happy'),
    (2, '累',       '累',       'lei4',               'lèi',            'tired'),
    (2, '离',       '離',       'li2',                'lí',             'leave; depart; go away; apart from'),
    (2, '两',       '兩',       'liang3',             'liǎng',          'two; 2; both; (unit of weight equal to 50 grams)'),
    (2, '零',       '零',       'ling2',              'líng',           'zero; remnant'),
    (2, '路',       '路',       'lu4',                'lù',             'road; path; journey; route'),
    (2, '旅游',     '旅游',     'lv3you2',            'lǚyóu',          'trip; journey; tour'),
    (2, '卖',       '賣',       'mai4',               'mài',            'to sell'),
    (2, '慢',       '慢',       'man4',               'màn',            'slow'),
    (2, '忙',       '忙',       'mang2',              'máng',           'busy'),
    (2, '每',       '每',       'mei3',               'měi',            'each; every'),
    (2, '妹妹',     '妹妹',     'mei4mei5',           'mèimei',         'younger sister'),
    (2, '门',       '門',       'men2',               'mén',            'door; opening; gate (Kangxi radical 169)'),
    (2, '面条',     '面條',     'mian4tiao2',         'miàntiáo',       'noodles'),
    (2, '男',       '男',       'nan2',               'nán',            'male'),
    (2, '您',       '您',       'nin2',               'nín',            'you (polite)'),
    (2, '牛奶',     '牛奶',     'niu2nai3',           'niúnǎi',         'cow''s milk'),
    (2, '女',       '女',       'nv3',                'nǚ',             'woman; female (Kangxi radical 38)'),
    (2, '旁边',     '旁邊',     'pang2bian1',         'pángbiān',       'side, beside'),
    (2, '跑步',     '跑步',     'pao3bu4',            'pǎobù',          'to run; to jog'),
    (2, '便宜',     '便宜',     'pian2yi5',           'piányi',         'cheap'),
    (2, '票',       '票',       'piao4',              'piào',           'ticket; bank note; a vote'),
    (2, '妻子',     '妻子',     'qi1zi5',             'qīzi',           'wife'),
    (2, '起床',     '起床',     'qi3chuang2',         'qǐ chuáng',      'get out of bed'),
    (2, '千',       '千',       'qian1',              'qiān',           'one thousand'),
    (2, '铅笔',     '鉛筆',     'qian1bi3',           'qiānbǐ',         'pencil'),
    (2, '晴',       '晴',       'qing2',              'qíng',           'clear; fine (as of weather)'),
    (2, '去年',     '去年',     'qu4nian2',           'qùnián',         'last year'),
    (2, '让',       '讓',       'rang4',              'ràng',           'ask; let; yield'),
    (2, '日',       '日',       'ri4',                'rì',             'sun; day; date; time (Kangxi radical 72)'),
    (2, '上班',     '上班',     'shang4ban1',         'shàngbān',       'go to work; be on duty'),
    (2, '身体',     '身體',     'shen1ti3',           'shēntǐ',         'health; (human) body'),
    (2, '生病',     '生病',     'sheng1bing4',        'shēngbìng',      'get sick; fall ill'),
    (2, '生日',     '生日',     'sheng1ri4',          'shēngrì',        'birthday'),
    (2, '时间',     '時間',     'shi2jian1',          'shíjiān',        'time; period'),
    (2, '事情',     '事情',     'shi4qing5',          'shìqing',        'matter; affair; thing; business'),
    (2, '手表',     '手表',     'shou3biao3',         'shǒubiǎo',       'wristwatch'),
    (2, '手机',     '手機',     'shou3ji1',           'shǒujī',         'mobile (cell) phone'),
    (2, '说话',     '說話',     'shuo1hua4',          'shuōhuà',        'to talk; speak'),
    (2, '送',       '送',       'song4',              'sòng',           'deliver; to carry; to give; send'),
    (2, '虽然',     '雖然',     'sui1ran2',           'suīrán',         'although; even though'),
    (2, '但是',     '但是',     'dan4shi4',           'dànshì',         'but; however'),
    (2, '它',       '它',       'ta1',                'tā',             'it'),
    (2, '踢足球',   '踢足球',   'ti1zu2qiu2',         'tīzúqiú',        'to play football/soccer'),
    (2, '题',       '題',       'ti2',                'tí',             'topic; subject; question on a test or assignment'),
    (2, '跳舞',     '跳舞',     'tiao4wu3',           'tiàowǔ',         'to dance'),
    (2, '外',       '外',       'wai4',               'wài',            'outer; outside; in addition; foreign'),
    (2, '完',       '完',       'wan2',               'wán',            'to finish; be over; complete'),
    (2, '玩',       '玩',       'wan2',               'wán',            'to play; have a good time; visit; enjoy'),
    (2, '晚上',     '晚上',     'wan3shang5',         'wǎnshang',       'evening; night'),
    (2, '往',       '往',       'wang3',              'wǎng',           'to go (in a direction); towards; in the past'),
    (2, '为什么',   '為什麼',   'wei4shen2me5',       'wèishénme',      'why?; for what reason?'),
    (2, '问',       '問',       'wen4',               'wèn',            'ask; inquire'),
    (2, '问题',     '問題',     'wen4ti2',            'wèntí',          'question; problem'),
    (2, '西瓜',     '西瓜',     'xi1gua1',            'xīguā',          'watermelon'),
    (2, '希望',     '希望',     'xi1wang4',           'xīwàng',         'to hope; wish for; to desire'),
    (2, '洗',       '洗',       'xi3',                'xǐ',             'to wash; bathe'),
    (2, '小时',     '小時',     'xiao3shi2',          'xiǎoshí',        'hour'),
    (2, '笑',       '笑',       'xiao4',              'xiào',           'to laugh; to smile'),
    (2, '新',       '新',       'xin1',               'xīn',            'new; Xinjiang autonomous region (abbreviation)'),
    (2, '姓',       '姓',       'xing4',              'xìng',           'surname; family name'),
    (2, '休息',     '休息',     'xiu1xi5',            'xiūxi',          'to rest; take a break'),
    (2, '雪',       '雪',       'xue3',               'xuě',            'snow'),
    (2, '颜色',     '顏色',     'yan2se4',            'yánsè',          'color'),
    (2, '眼睛',     '眼睛',     'yan3jing5',          'yǎnjing',        'eye'),
    (2, '羊肉',     '羊肉',     'yang2rou4',          'yángròu',        'mutton; lamb'),
    (2, '药',       '藥',       'yao4',               'yào',            'medicine; drug; cure; chemical'),
    (2, '要',       '要',       'yao4',               'yào',            'to want; to need; will/shall; important'),
    (2, '也',       '也',       'ye3',                'yě',             'also; too'),
    (2, '一起',     '一起',     'yi4qi3',             'yìqǐ',           'together; in the same place'),
    (2, '一下',     '一下',     'yi2xia4',            'yíxià',          'a little bit/while; one time; once'),
    (2, '已经',     '已經',     'yi3jing5',           'yǐjing',         'already'),
    (2, '意思',     '意思',     'yi4si5',             'yìsi',           'meaning; idea; opinion'),
    (2, '因为',     '因為',     'yin1wei4',           'yīnwèi',         'because'),
    (2, '所以',     '所以',     'suo3yi3',            'suǒyǐ',          'so; therefore; as a result'),
    (2, '阴',       '陰',       'yin1',               'yīn',            'cloudy (weather); yin (the negative principle of Yin and Yang); secret; the moon; negative; shade'),
    (2, '游泳',     '游泳',     'you2yong3',          'yóuyǒng',        'to swim'),
    (2, '右边',     '右邊',     'you4bian5',          'yòubian',        'the right (as opposed to left) side'),
    (2, '鱼',       '魚',       'yu2',                'yú',             'fish (Kangxi radical 195)'),
    (2, '远',       '遠',       'yuan3',              'yuǎn',           'far; distant; remote'),
    (2, '运动',     '運動',     'yun4dong4',          'yùndòng',        '(physical) exercise; movement; sports; campaign'),
    (2, '再',       '再',       'zai4',               'zài',            'again; once more'),
    (2, '早上',     '早上',     'zao3shang5',         'zǎoshang',       '(early) morning'),
    (2, '丈夫',     '丈夫',     'zhang4fu5',          'zhàngfu',        'husband; man'),
    (2, '找',       '找',       'zhao3',              'zhǎo',           'try to find; look for; seek; to give change'),
    (2, '着',       '著',       'zhe5',               'zhe',            '-ing (indicating action in progress)'),
    (2, '真',       '真',       'zhen1',              'zhēn',           'real; true; genuine'),
    (2, '正在',     '正在',     'zheng4zai4',         'zhèngzài',       'in the process of (doing something); currently'),
    (2, '知道',     '知道',     'zhi1dao5',           'zhīdao',         'know; be aware of'),
    (2, '准备',     '准備',     'zhun3bei4',          'zhǔnbèi',        'prepare; get ready'),
    (2, '走',       '走',       'zou3',               'zǒu',            'to walk; to go; to move (Kangxi radical 156)'),
    (2, '最',       '最',       'zui4',               'zuì',            'the most; -est; (indicator for superlative)'),
    (2, '左边',     '左邊',     'zuo3bian5',          'zuǒbian',        'the left side; the left')
;

COMMIT TRANSACTION;
