BEGIN TRANSACTION;

INSERT INTO vocabulary (
    hsk_level,
    hans,
    hant,
    pinyin_input,
    pinyin_display,
    definition,
    secondary_definitions
)
VALUES
    (2, '吧',       '吧',       'ba5',                'ba',             'suggestion particle',                'bar (serving drinks, etc.)'),
    (2, '白',       '白',       'bai2',               'bái',            'white',                              'snowy; pure; bright; empty'),
    (2, '百',       '百',       'bai3',               'bǎi',            'hundred',                            NULL),
    (2, '帮助',     '幫助',     'bang1zhu4',          'bāngzhù',        'to help',                            'to assist; to aid'),
    (2, '报纸',     '報紙',     'bao4zhi3',           'bàozhǐ',         'newspaper',                          NULL),
    (2, '比',       '比',       'bi3',                'bǐ',             'to compare',                         'comparison marker'),
    (2, '别',       '別',       'bie2',               'bié',            'don''t',                             'other; to depart; difference; to distinguish'),
    (2, '宾馆',     '賓館',     'bin1guan3',          'bīnguǎn',        'hotel',                              'guesthouse'),
    (2, '长',       '長',       'chang2',             'cháng',          'long',                               'length'),
    (2, '长',       '長',       'zhang3',             'zhǎng',          'to grow',                            'elder; chief'),
    (2, '唱歌',     '唱歌',     'chang4ge1',          'chànggē',        'to sing',                            NULL),
    (2, '出',       '出',       'chu1',               'chū',            'to go out',                          'to occur'),
    (2, '穿',       '穿',       'chuan1',             'chuān',          'to wear',                            'to put on; to penetrate'),
    (2, '次',       '次',       'ci4',                'cì',             'measure word for occurrences',       'nth; order'),
    (2, '从',       '從',       'cong2',              'cóng',           'from',                               'to obey; to observe'),
    (2, '错',       '錯',       'cuo4',               'cuò',            'mistake',                            'error; wrong; to miss an opportunity'),
    (2, '打篮球',   '打籃球',   'da3 lan2qiu2',       'dǎ lánqiú',      'to play basketball',                 NULL),
    (2, '大家',     '大家',     'da4jia1',            'dàjiā',          'everyone',                           NULL),
    (2, '但是',     '但是',     'dan4shi4',           'dànshì',         'but',                                'however'),
    (2, '到',       '到',       'dao4',               'dào',            'to arrive',                          'until'),
    (2, '得',       '得',       'de5',                'de',             'complement particle',                NULL),
    (2, '等',       '等',       'deng3',              'děng',           'to wait',                            'rank; equal; etc.'),
    (2, '弟弟',     '弟弟',     'di4di5',             'dìdi',           'younger brother',                    NULL),
    (2, '第一',     '第一',     'di4yi1',             'dìyī',           'first',                              'number one'),
    (2, '懂',       '懂',       'dong3',              'dǒng',           'to understand',                      'to know'),
    (2, '对',       '對',       'dui4',               'duì',            'correct',                            'a pair; to face; towards'),
    (2, '房间',     '房間',     'fang2jian1',         'fángjiān',       'room',                               NULL),
    (2, '非常',     '非常',     'fei1chang2',         'fēicháng',       'very',                               'extremely; extraordinary'),
    (2, '服务员',   '服務員',   'fu2wu4yuan2',        'fúwùyuán',       'waiter; waitress',                   'server; attendant'),
    (2, '高',       '高',       'gao1',               'gāo',            'tall',                               'high'),
    (2, '告诉',     '告訴',     'gao4su5',            'gàosu',          'to tell',                            'to inform'),
    (2, '哥哥',     '哥哥',     'ge1ge5',             'gēge',           'older brother',                      NULL),
    (2, '给',       '給',       'gei3',               'gěi',            'to give',                            'to grant; passive particle'),
    (2, '公共汽车', '公共汽車', 'gong1gong4 qi4che1', 'gōnggòng qìchē', 'bus',                                NULL),
    (2, '公司',     '公司',     'gong1si1',           'gōngsī',         'company',                            'corporation'),
    (2, '贵',       '貴',       'gui4',               'guì',            'expensive',                          'noble; honorable'),
    (2, '过',       '過',       'guo4',               'guò',            'to pass',                            'to cross; to go over; past experience marker'),
    (2, '还',       '還',       'hai2',               'hái',            'still',                              'yet; in addition; even'),
    (2, '孩子',     '孩子',     'hai2zi5',            'háizi',          'child',                              'son or daughter'),
    (2, '好吃',     '好吃',     'hao3chi1',           'hǎochī',         'tasty',                              'delicious'),
    (2, '黑',       '黑',       'hei1',               'hēi',            'black',                              'dark'),
    (2, '红',       '紅',       'hong2',              'hóng',           'red',                                'popular; bonus'),
    (2, '火车站',   '火車站',   'huo3che1zhan4',      'huǒchēzhàn',     'train station',                      NULL),
    (2, '机场',     '機場',     'ji1chang3',          'jīchǎng',        'airport',                            NULL),
    (2, '鸡蛋',     '雞蛋',     'ji1dan4',            'jīdàn',          'egg',                                'chicken egg'),
    (2, '件',       '件',       'jian4',              'jiàn',           'measure word for clothes and items', NULL),
    (2, '教室',     '教室',     'jiao4shi4',          'jiàoshì',        'classroom',                          NULL),
    (2, '姐姐',     '姐姐',     'jie3jie5',           'jiějie',         'older sister',                       NULL),
    (2, '介绍',     '介紹',     'jie4shao4',          'jièshào',        'to introduce',                       'to recommend'),
    (2, '进',       '進',       'jin4',               'jìn',            'to enter',                           'to come in'),
    (2, '近',       '近',       'jin4',               'jìn',            'near',                               'close to'),
    (2, '就',       '就',       'jiu4',               'jiù',            'then',                               'at once; just; only; with regard to'),
    (2, '觉得',     '覺得',     'jue2de5',            'juéde',          'to feel',                            'to think'),
    (2, '咖啡',     '咖啡',     'ka1fei1',            'kāfēi',          'coffee',                             NULL),
    (2, '开始',     '開始',     'kai1shi3',           'kāishǐ',         'to begin',                           'to start; beginning'),
    (2, '考试',     '考試',     'kao3shi4',           'kǎoshì',         'exam',                               'test; to take an exam'),
    (2, '可能',     '可能',     'ke3neng2',           'kěnéng',         'maybe',                              'possible; possibly'),
    (2, '可以',     '可以',     'ke3yi3',             'kěyǐ',           'can',                                'may; okay'),
    (2, '课',       '課',       'ke4',                'kè',             'class',                              'lesson; subject; course'),
    (2, '快',       '快',       'kuai4',              'kuài',           'fast',                               'quick; swift'),
    (2, '快乐',     '快樂',     'kuai4le4',           'kuàilè',         'happy',                              NULL),
    (2, '累',       '累',       'lei4',               'lèi',            'tired',                              NULL),
    (2, '离',       '離',       'li2',                'lí',             'away from',                          'to leave; to depart; apart from'),
    (2, '两',       '兩',       'liang3',             'liǎng',          'two',                                'both'),
    (2, '零',       '零',       'ling2',              'líng',           'zero',                               NULL),
    (2, '路',       '路',       'lu4',                'lù',             'road',                               'path; route; journey'),
    (2, '旅游',     '旅游',     'lv3you2',            'lǚyóu',          'to travel',                          'trip; tour'),
    (2, '卖',       '賣',       'mai4',               'mài',            'to sell',                            NULL),
    (2, '慢',       '慢',       'man4',               'màn',            'slow',                               NULL),
    (2, '忙',       '忙',       'mang2',              'máng',           'busy',                               NULL),
    (2, '每',       '每',       'mei3',               'měi',            'every',                              'each'),
    (2, '妹妹',     '妹妹',     'mei4mei5',           'mèimei',         'younger sister',                     NULL),
    (2, '门',       '門',       'men2',               'mén',            'door',                               'gate; opening'),
    (2, '面条',     '面條',     'mian4tiao2',         'miàntiáo',       'noodles',                            NULL),
    (2, '男',       '男',       'nan2',               'nán',            'male',                               'man'),
    (2, '您',       '您',       'nin2',               'nín',            'you (polite)',                        NULL),
    (2, '牛奶',     '牛奶',     'niu2nai3',           'niúnǎi',         'milk',                               'cow''s milk'),
    (2, '女',       '女',       'nv3',                'nǚ',             'female',                             'woman'),
    (2, '旁边',     '旁邊',     'pang2bian1',         'pángbiān',       'beside',                             'next to; side'),
    (2, '跑步',     '跑步',     'pao3bu4',            'pǎobù',          'to run',                             'to jog'),
    (2, '便宜',     '便宜',     'pian2yi5',           'piányi',         'cheap',                              'inexpensive'),
    (2, '票',       '票',       'piao4',              'piào',           'ticket',                             'bank note; a vote'),
    (2, '妻子',     '妻子',     'qi1zi5',             'qīzi',           'wife',                               NULL),
    (2, '起床',     '起床',     'qi3chuang2',         'qǐ chuáng',      'to get out of bed',                  NULL),
    (2, '千',       '千',       'qian1',              'qiān',           'one thousand',                       NULL),
    (2, '铅笔',     '鉛筆',     'qian1bi3',           'qiānbǐ',         'pencil',                             NULL),
    (2, '晴',       '晴',       'qing2',              'qíng',           'sunny',                              'clear; fine weather'),
    (2, '去年',     '去年',     'qu4nian2',           'qùnián',         'last year',                          NULL),
    (2, '让',       '讓',       'rang4',              'ràng',           'to let',                             'to ask; to yield'),
    (2, '日',       '日',       'ri4',                'rì',             'day',                                'sun; date'),
    (2, '上班',     '上班',     'shang4ban1',         'shàngbān',       'to go to work',                      'to be on duty'),
    (2, '身体',     '身體',     'shen1ti3',           'shēntǐ',         'body',                               'health'),
    (2, '生病',     '生病',     'sheng1bing4',        'shēngbìng',      'to get sick',                        'to fall ill'),
    (2, '生日',     '生日',     'sheng1ri4',          'shēngrì',        'birthday',                           NULL),
    (2, '时间',     '時間',     'shi2jian1',          'shíjiān',        'time',                               'period'),
    (2, '事情',     '事情',     'shi4qing5',          'shìqing',        'matter',                             'affair; thing; business'),
    (2, '手表',     '手表',     'shou3biao3',         'shǒubiǎo',       'wristwatch',                         NULL),
    (2, '手机',     '手機',     'shou3ji1',           'shǒujī',         'mobile phone',                       'cell phone'),
    (2, '说话',     '說話',     'shuo1hua4',          'shuōhuà',        'to talk',                            'to speak'),
    (2, '送',       '送',       'song4',              'sòng',           'to give (as a gift)',                 'to deliver; to carry; to send'),
    (2, '所以',     '所以',     'suo3yi3',            'suǒyǐ',          'so',                                 'therefore; as a result'),
    (2, '虽然',     '雖然',     'sui1ran2',           'suīrán',         'although',                           'even though'),
    (2, '它',       '它',       'ta1',                'tā',             'it',                                 NULL),
    (2, '踢足球',   '踢足球',   'ti1zu2qiu2',         'tīzúqiú',        'to play football',                   'to play soccer'),
    (2, '题',       '題',       'ti2',                'tí',             'question',                           'topic; subject'),
    (2, '跳舞',     '跳舞',     'tiao4wu3',           'tiàowǔ',         'to dance',                           NULL),
    (2, '外',       '外',       'wai4',               'wài',            'outside',                            'outer; foreign; in addition'),
    (2, '完',       '完',       'wan2',               'wán',            'to finish',                          'to complete; to be over'),
    (2, '玩',       '玩',       'wan2',               'wán',            'to play',                            'to have a good time; to visit; to enjoy'),
    (2, '晚上',     '晚上',     'wan3shang5',         'wǎnshang',       'evening',                            'night'),
    (2, '往',       '往',       'wang3',              'wǎng',           'towards',                            'to go in a direction; in the past'),
    (2, '为什么',   '為什麼',   'wei4shen2me5',       'wèishénme',      'why',                                'for what reason'),
    (2, '问',       '問',       'wen4',               'wèn',            'to ask',                             'to inquire'),
    (2, '问题',     '問題',     'wen4ti2',            'wèntí',          'question',                           'problem'),
    (2, '西瓜',     '西瓜',     'xi1gua1',            'xīguā',          'watermelon',                         NULL),
    (2, '希望',     '希望',     'xi1wang4',           'xīwàng',         'to hope',                            'to wish for; to desire'),
    (2, '洗',       '洗',       'xi3',                'xǐ',             'to wash',                            'to bathe'),
    (2, '小时',     '小時',     'xiao3shi2',          'xiǎoshí',        'hour',                               NULL),
    (2, '笑',       '笑',       'xiao4',              'xiào',           'to smile',                           'to laugh'),
    (2, '新',       '新',       'xin1',               'xīn',            'new',                                NULL),
    (2, '姓',       '姓',       'xing4',              'xìng',           'surname',                            'family name'),
    (2, '休息',     '休息',     'xiu1xi5',            'xiūxi',          'to rest',                            'to take a break'),
    (2, '雪',       '雪',       'xue3',               'xuě',            'snow',                               NULL),
    (2, '颜色',     '顏色',     'yan2se4',            'yánsè',          'color',                              NULL),
    (2, '眼睛',     '眼睛',     'yan3jing5',          'yǎnjing',        'eye',                                NULL),
    (2, '羊肉',     '羊肉',     'yang2rou4',          'yángròu',        'lamb',                               'mutton'),
    (2, '药',       '藥',       'yao4',               'yào',            'medicine',                           'drug; cure'),
    (2, '要',       '要',       'yao4',               'yào',            'to want',                            'to need; will; shall; important'),
    (2, '也',       '也',       'ye3',                'yě',             'also',                               'too'),
    (2, '一起',     '一起',     'yi4qi3',             'yìqǐ',           'together',                           'in the same place'),
    (2, '一下',     '一下',     'yi2xia4',            'yíxià',          'a little bit',                       'once; one moment'),
    (2, '已经',     '已經',     'yi3jing5',           'yǐjing',         'already',                            NULL),
    (2, '意思',     '意思',     'yi4si5',             'yìsi',           'meaning',                            'idea; opinion'),
    (2, '因为',     '因為',     'yin1wei4',           'yīnwèi',         'because',                            NULL),
    (2, '阴',       '陰',       'yin1',               'yīn',            'cloudy',                             'overcast'),
    (2, '游泳',     '游泳',     'you2yong3',          'yóuyǒng',        'to swim',                            NULL),
    (2, '右边',     '右邊',     'you4bian5',          'yòubian',        'right side',                         'the right'),
    (2, '鱼',       '魚',       'yu2',                'yú',             'fish',                               NULL),
    (2, '远',       '遠',       'yuan3',              'yuǎn',           'far',                                'distant; remote'),
    (2, '运动',     '運動',     'yun4dong4',          'yùndòng',        'exercise',                           'sports; movement; campaign'),
    (2, '再',       '再',       'zai4',               'zài',            'again',                              'once more'),
    (2, '早上',     '早上',     'zao3shang5',         'zǎoshang',       'morning',                            'early morning'),
    (2, '丈夫',     '丈夫',     'zhang4fu5',          'zhàngfu',        'husband',                            NULL),
    (2, '找',       '找',       'zhao3',              'zhǎo',           'to look for',                        'to seek; to give change'),
    (2, '着',       '著',       'zhe5',               'zhe',            'progressive aspect marker',          '-ing; indicating action in progress'),
    (2, '真',       '真',       'zhen1',              'zhēn',           'real',                               'true; genuine'),
    (2, '正在',     '正在',     'zheng4zai4',         'zhèngzài',       'currently doing',                    'in the process of'),
    (2, '知道',     '知道',     'zhi1dao5',           'zhīdao',         'to know',                            'to be aware of'),
    (2, '准备',     '准備',     'zhun3bei4',          'zhǔnbèi',        'to prepare',                         'to get ready'),
    (2, '走',       '走',       'zou3',               'zǒu',            'to walk',                            'to go; to move; to leave'),
    (2, '最',       '最',       'zui4',               'zuì',            'most',                               'superlative marker'),
    (2, '左边',     '左邊',     'zuo3bian5',          'zuǒbian',        'left side',                          'the left')
;

COMMIT TRANSACTION;
