BEGIN TRANSACTION;

INSERT INTO vocabulary (
    hsk_level,
    hans,
    hant,
    pinyin_input,
    pinyin_display,
    definition
)
VALUES
    (3, '阿姨',     '阿姨',     'a1yi2',              'āyí',            'auntie; step-mother; mother''s younger sister'),
    (3, '啊',       '啊',       'a5',                 'a',              'ah; (particle showing elation, doubt, puzzled surprise, or approval)'),
    (3, '矮',       '矮',       'ai3',                'ǎi',             'short; low'),
    (3, '爱好',     '愛好',     'ai4hao4',            'àihào',          'hobby; fond of; to like; interest'),
    (3, '安静',     '安靜',     'an1jing4',           'ānjìng',         'quiet; peaceful; calm'),
    (3, '把',       '把',       'ba3',                'bǎ',             '(mw for things with handles); (pretransitive particle); to hold'),
    (3, '班',       '班',       'ban1',               'bān',            'team; class; squad'),
    (3, '搬',       '搬',       'ban1',               'bān',            'to move; to transport'),
    (3, '办法',     '辦法',     'ban4fa3',            'bànfǎ',          'method; way (of doing something)'),
    (3, '办公室',   '辦公室',   'ban4gong1shi4',      'bàngōngshì',     'office'),
    (3, '半',       '半',       'ban4',               'bàn',            'half; semi-; incomplete'),
    (3, '帮忙',     '幫忙',     'bang1mang2',         'bāngmáng',       'to help'),
    (3, '包',       '包',       'bao1',               'bāo',            'to cover; to wrap; to hold; include; (mw for containers, packages, etc.)'),
    (3, '饱',       '飽',       'bao3',               'bǎo',            'eat until full; satisfied'),
    (3, '北方',     '北方',     'bei3fang1',          'běifāng',        'north; the northern part of the country'),
    (3, '被',       '被',       'bei4',               'bèi',            'by (indicates passive voice sentences); a quilt/blanket'),
    (3, '鼻子',     '鼻子',     'bi2zi5',             'bízi',           'nose'),
    (3, '比较',     '比較',     'bi3jiao4',           'bǐjiào',         'compare; contrast; relatively'),
    (3, '比赛',     '比賽',     'bi3sai4',            'bǐsài',          '(sports) match; competition'),
    (3, '笔记本',   '筆記本',   'bi3ji4ben3',         'bǐjìběn',        'notebook'),
    (3, '必须',     '必須',     'bi4xu1',             'bìxū',           'must; have to'),
    (3, '变化',     '變化',     'bian4hua4',          'biànhuà',        'change'),
    (3, '别人',     '別人',     'bie2ren5',           'biéren',         'other people; others'),
    (3, '冰箱',     '冰箱',     'bing1xiang1',        'bīngxiāng',      'refrigerator'),
    (3, '不但',     '不但',     'bu2dan4',            'búdàn',          'not only'),
    (3, '而且',     '而且',     'er2qie3',            'érqiě',          'moreover; in addition; as well as'),
    (3, '菜单',     '菜單',     'cai4dan1',           'càidān',         'menu'),
    (3, '参加',     '參加',     'can1jia1',           'cānjiā',         'participate; join; take part in'),
    (3, '草',       '草',       'cao3',               'cǎo',            'grass; straw; draft (of a document)'),
    (3, '层',       '層',       'ceng2',              'céng',           '(mw for layers, floors of buildings)'),
    (3, '差',       '差',       'cha4',               'chà',            'differ from; fall short of; poor; inferio'),
    (3, '超市',     '超市',     'chao1shi4',          'chāoshì',        'supermarket'),
    (3, '衬衫',     '襯衫',     'chen4shan1',         'chènshān',       'shirt; blouse'),
    (3, '成绩',     '成績',     'cheng2ji4',          'chéngjì',        'achievement; success; results (of work or study)'),
    (3, '城市',     '城市',     'cheng2shi4',         'chéngshì',       'city or town'),
    (3, '迟到',     '遲到',     'chi2dao4',           'chídào',         'arrive late'),
    (3, '除了',     '除了',     'chu2le5',            'chúle',          'besides; except for; aside from; in addition to'),
    (3, '船',       '船',       'chuan2',             'chuán',          'a boat; vessel; ship'),
    (3, '春',       '春',       'chun1',              'chūn',           'spring (season); joyful'),
    (3, '词典',     '詞典',     'ci2dian3',           'cídiǎn',         'dictionary'),
    (3, '聪明',     '聰明',     'cong1ming5',         'cōngming',       'intelligent; clever; bright; smart'),
    (3, '打扫',     '打掃',     'da3sao3',            'dǎsǎo',          'to clean; to sweep'),
    (3, '打算',     '打算',     'da3suan4',           'dǎsuàn',         'to plan; intend'),
    (3, '带',       '帶',       'dai4',               'dài',            'band; belt; ribbon; carry; bring; take along; bring up (kids)'),
    (3, '担心',     '擔心',     'dan1xin1',           'dānxīn',         'to worry; feel anxious'),
    (3, '蛋糕',     '蛋糕',     'dan4gao1',           'dàngāo',         'cake'),
    (3, '当然',     '當然',     'dang1ran2',          'dāngrán',        'of course; naturally'),
    (3, '地',       '地',       'di4, de5',           'dì, de',         'earth; ground | (adverbial particle)'),
    (3, '灯',       '燈',       'deng1',              'dēng',           'lamp; light'),
    (3, '地方',     '地方',     'di4fang5',           'dìfang',         'place; space; room; part, (fāng: local; regional)'),
    (3, '地铁',     '地鐵',     'di4tie3',            'dìtiě',          'subway'),
    (3, '地图',     '地圖',     'di4tu2',             'dìtú',           'map'),
    (3, '电梯',     '電梯',     'dian4ti1',           'diàntī',         'elevator'),
    (3, '电子邮件', '電子郵件', 'dian4zi3 you2jian4', 'diànzǐ yóujiàn', 'email'),
    (3, '东',       '東',       'dong1',              'dōng',           'East'),
    (3, '冬',       '冬',       'dong1',              'dōng',           'winter'),
    (3, '动物',     '動物',     'dong4wu4',           'dòngwù',         'animal'),
    (3, '短',       '短',       'duan3',              'duǎn',           'short (in length, duration, or height); lack'),
    (3, '段',       '段',       'duan4',              'duàn',           'paragraph; segment; section'),
    (3, '锻炼',     '鍛煉',     'duan4lian4',         'duànliàn',       'to exercise; work out; toughen; to temper'),
    (3, '多么',     '多麼',     'duo1me5',            'duōme',          'how (wonderful, etc.); what (a great idea)'),
    (3, '饿',       '餓',       'e4',                 'è',              'hungry'),
    (3, '耳朵',     '耳朵',     'er3duo5',            'ěrduo',          'ear'),
    (3, '发',       '發',       'fa1, fa4',           'fā, fà',         'send out; to issue; to show (one''s feelings) | hair'),
    (3, '发烧',     '發燒',     'fa1shao1',           'fāshāo',         'have a fever'),
    (3, '发现',     '發現',     'fa1xian4',           'fāxiàn',         'discover; to find'),
    (3, '方便',     '方便',     'fang1bian4',         'fāngbiàn',       'convenient'),
    (3, '放',       '放',       'fang4',              'fàng',           'put; to place; to release; to free'),
    (3, '放心',     '放心',     'fang4xin1',          'fàngxīn',        'relax; feel relieved; rest assured'),
    (3, '分',       '分',       'fen1, fen4',         'fēn, fèn',       'divide; part; minute; cent | component; share; ingredient'),
    (3, '附近',     '附近',     'fu4jin4',            'fùjìn',          '(in the) vicinity; nearby; neighboring'),
    (3, '复习',     '復習',     'fu4xi2',             'fùxí',           'revise; to review'),
    (3, '干净',     '干淨',     'gan1jing4',          'gānjìng',        'clean; neat and tidy'),
    (3, '感冒',     '感冒',     'gan3mao4',           'gǎnmào',         'catch cold; (common) cold'),
    (3, '感兴趣',   '感興趣',   'gan3 xing4qu4',      'gǎn xìngqù',     'be interested in'),
    (3, '刚才',     '剛才',     'gang1cai2',          'gāngcái',        'just now; a moment ago'),
    (3, '个子',     '個子',     'ge4zi5',             'gèzi',           'height; stature; build'),
    (3, '根据',     '根據',     'gen1ju4',            'gēnjù',          'according to; based on; basis'),
    (3, '跟',       '跟',       'gen1',               'gēn',            'to follow; go with; heel'),
    (3, '更',       '更',       'geng4',              'gèng',           'more; even mor'),
    (3, '公斤',     '公斤',     'gong1jin1',          'gōngjīn',        'kilogram'),
    (3, '公园',     '公園',     'gong1yuan2',         'gōngyuán',       'public park'),
    (3, '故事',     '故事',     'gu4shi5',            'gùshi',          'story; tale'),
    (3, '刮风',     '刮風',     'gua1feng1',          'guāfēng',        'windy; to blow (wind)'),
    (3, '关',       '關',       'guan1',              'guān',           'to close; shut; concern; relationship; turn off; mountain pass'),
    (3, '关系',     '關系',     'guan1xi5',           'guānxi',         'relation; to concern'),
    (3, '关心',     '關心',     'guan1xin1',          'guānxīn',        'concerned about/with'),
    (3, '关于',     '關於',     'guan1yu2',           'guānyú',         'about; regarding; concerning'),
    (3, '国家',     '國家',     'guo2jia1',           'guójiā',         'country; state; nation'),
    (3, '过',       '過',       'guo4',               'guò',            'to pass; to cross; go over; (indicates a past experience)'),
    (3, '过去',     '過去',     'guo4qu4',            'guòqù',          'in the past; formerly'),
    (3, '还是',     '還是',     'hai2shi5',           'háishi',         'or; still; nevertheless; had better'),
    (3, '害怕',     '害怕',     'hai4pa4',            'hàipà',          'afraid of; to fear'),
    (3, '黑板',     '黑板',     'hei1ban3',           'hēibǎn',         'blackboard'),
    (3, '后来',     '后來',     'hou4lai2',           'hòulái',         'afterwards; after; later'),
    (3, '护照',     '護照',     'hu4zhao4',           'hùzhào',         'passport'),
    (3, '花',       '花',       'hua1',               'huā',            'flower; blossom; spend money; cost'),
    (3, '画',       '畫',       'hua4',               'huà',            'draw; picture; painting'),
    (3, '坏',       '壞',       'huai4',              'huài',           'bad; broken'),
    (3, '欢迎',     '歡迎',     'huan1ying2',         'huānyíng',       'to welcome; greet'),
    (3, '还',       '還',       'hai2',               'hái',            'still; yet; in addition; even'),
    (3, '环境',     '環境',     'huan2jing4',         'huánjìng',       'environment; surroundings'),
    (3, '换',       '換',       'huan4',              'huàn',           'change; to exchange; to barter; to trade'),
    (3, '黄河',     '黃河',     'huang2he2',          'huánghé',        'Yellow River'),
    (3, '回答',     '回答',     'hui2da2',            'huídá',          'to reply; to answer'),
    (3, '会议',     '會議',     'hui4yi4',            'huìyì',          'meeting; conference'),
    (3, '或者',     '或者',     'huo4zhe3',           'huòzhě',         'or; possible; maybe; perhaps'),
    (3, '几乎',     '幾乎',     'ji1hu1',             'jīhū',           'almost'),
    (3, '机会',     '機會',     'ji1hui4',            'jīhuì',          'opportunity; chance; occasion'),
    (3, '极',       '極',       'ji2',                'jí',             'an extreme; pole; very'),
    (3, '记得',     '記得',     'ji4de5',             'jìde',           'remember'),
    (3, '季节',     '季節',     'ji4jie2',            'jìjié',          'season; time; period'),
    (3, '检查',     '檢查',     'jian3cha2',          'jiǎnchá',        'to check; examine; inspect'),
    (3, '简单',     '簡單',     'jian3dan1',          'jiǎndān',        'simple; not complicated'),
    (3, '见面',     '見面',     'jian4mian4',         'jiànmiàn',       'meet/see somebody; meeting'),
    (3, '健康',     '健康',     'jian4kang1',         'jiànkāng',       'health; healthy'),
    (3, '讲',       '講',       'jiang3',             'jiǎng',          'to talk; to lecture; to explain; a speech'),
    (3, '教',       '教',       'jiao1, jiao4',       'jiāo, jiào',     'teach; instruct | religion; teaching'),
    (3, '角',       '角',       'jiao3, jue2',        'jiǎo, jué',      'horn; angle; unit of money (1/10 yuan); corner (Kangxi radical 148) | role (theater)'),
    (3, '脚',       '腳',       'jiao3',              'jiǎo',           'foot (body part)'),
    (3, '接',       '接',       'jie1',               'jiē',            'connect; to meet; to pick up (somebody); to receive'),
    (3, '街道',     '街道',     'jie1dao4',           'jiēdào',         'street'),
    (3, '节目',     '節目',     'jie2mu4',            'jiémù',          'program; item (on a program)'),
    (3, '节日',     '節日',     'jie2ri4',            'jiérì',          'holiday; festival'),
    (3, '结婚',     '結婚',     'jie2hun1',           'jiéhūn',         'get married'),
    (3, '结束',     '結束',     'jie2shu4',           'jiéshù',         'to end; to finish; conclude'),
    (3, '解决',     '解決',     'jie3jue2',           'jiějué',         'settle (a dispute); resolve; solve'),
    (3, '借',       '借',       'jie4',               'jiè',            'lend; borrow; excuse'),
    (3, '经常',     '經常',     'jing1chang2',        'jīngcháng',      'often; frequently; daily'),
    (3, '经过',     '經過',     'jing1guo4',          'jīngguò',        'to pass; go through; as a result of'),
    (3, '经理',     '經理',     'jing1li3',           'jīnglǐ',         'manager; director'),
    (3, '久',       '久',       'jiu3',               'jiǔ',            'long (time)'),
    (3, '旧',       '舊',       'jiu4',               'jiù',            'old; past; used'),
    (3, '句子',     '句子',     'ju4zi5',             'jùzi',           'sentence'),
    (3, '决定',     '決定',     'jue2ding4',          'juédìng',        'decide; resolve'),
    (3, '可爱',     '可愛',     'ke3ai4',            'kěài',          'cute; lovely'),
    (3, '渴',       '渴',       'ke3',                'kě',             'thirsty'),
    (3, '刻',       '刻',       'ke4',                'kè',             'quarter (hour); (mw for short time intervals); carve; to cut'),
    (3, '客人',     '客人',     'ke4ren2',            'kèrén',          'guest; customer'),
    (3, '空调',     '空調',     'kong1tiao2',         'kōngtiáo',       'air conditioning'),
    (3, '口',       '口',       'kou3',               'kǒu',            'mouth (Kangxi radical 30)'),
    (3, '哭',       '哭',       'ku1',                'kū',             'cry; weep'),
    (3, '裤子',     '褲子',     'ku4zi5',             'kùzi',           'pants; trousers'),
    (3, '筷子',     '筷子',     'kuai4zi5',           'kuàizi',         'chopsticks'),
    (3, '蓝',       '藍',       'lan2',               'lán',            'blue'),
    (3, '老',       '老',       'lao3',               'lǎo',            'old; aged; tough; often (Kangxi radical 125)'),
    (3, '离开',     '離開',     'li2kai1',            'líkāi',          'leave; depart'),
    (3, '礼物',     '禮物',     'li3wu4',             'lǐwù',           'gift; present'),
    (3, '历史',     '歷史',     'li4shi3',            'lìshǐ',          'history'),
    (3, '脸',       '臉',       'lian3',              'liǎn',           'face'),
    (3, '练习',     '練習',     'lian4xi2',           'liànxí',         'practice; exercise'),
    (3, '辆',       '輛',       'liang4',             'liàng',          '(mw for vehicles)'),
    (3, '聊天',     '聊天',     'liao2tian1',         'liáotiān',       'to chat'),
    (3, '了解',     '了解',     'liao3jie3',          'liǎojiě',        'comprehend; understand; know; find out'),
    (3, '邻居',     '鄰居',     'lin2ju1',            'línjū',          'neighbor'),
    (3, '留学',     '留學',     'liu2xue2',           'liúxué',         'study abroad'),
    (3, '楼',       '樓',       'lou2',               'lóu',            'story; floor; (multi-story) building'),
    (3, '绿',       '綠',       'lv4',                'lǜ',             'green'),
    (3, '马',       '馬',       'ma3',                'mǎ',             'horse (Kangxi radical 187)'),
    (3, '马上',     '馬上',     'ma3shang4',          'mǎshàng',        'at once; immediately; right away'),
    (3, '满意',     '滿意',     'man3yi4',            'mǎnyì',          'satisfied; pleased'),
    (3, '帽子',     '帽子',     'mao4zi5',            'màozi',          'hat; cap'),
    (3, '米',       '米',       'mi3',                'mǐ',             'rice; meter (Kangxi radical 119)'),
    (3, '面包',     '面包',     'mian4bao1',          'miànbāo',        'bread'),
    (3, '明白',     '明白',     'ming2bai5',          'míngbai',        'clear; obvious; understand; explicit'),
    (3, '拿',       '拿',       'na2',                'ná',             'carry in your hand; seize; to catch'),
    (3, '奶奶',     '奶奶',     'nai3nai5',           'nǎinai',         'grandma; (informal) paternal grandmother'),
    (3, '南',       '南',       'nan2',               'nán',            'South'),
    (3, '难',       '難',       'nan2',               'nán',            'difficult'),
    (3, '难过',     '難過',     'nan2guo4',           'nánguò',         'be grieved; be sad; have a hard time'),
    (3, '年级',     '年級',     'nian2ji2',           'niánjí',         'grade; year (in school)'),
    (3, '年轻',     '年輕',     'nian2qing1',         'niánqīng',       'young'),
    (3, '鸟',       '鳥',       'niao3',              'niǎo',           'bird (Kangxi radical 196)'),
    (3, '努力',     '努力',     'nu3li4',             'nǔlì',           'to work hard; to strive'),
    (3, '爬山',     '爬山',     'pa2shan1',           'páshān',         'mountain climbing'),
    (3, '盘子',     '盤子',     'pan2zi5',            'pánzi',          'plate; dish; tray'),
    (3, '胖',       '胖',       'pang4',              'pàng',           'fat; plump'),
    (3, '皮鞋',     '皮鞋',     'pi2xie2',            'píxié',          'leather shoes'),
    (3, '啤酒',     '啤酒',     'pi2jiu3',            'píjiǔ',          'beer'),
    (3, '瓶子',     '瓶子',     'ping2zi5',           'píngzi',         'bottle'),
    (3, '其实',     '其實',     'qi2shi2',            'qíshí',          'actually; in fact'),
    (3, '其他',     '其他',     'qi2ta1',             'qítā',           'other; else'),
    (3, '奇怪',     '奇怪',     'qi2guai4',           'qíguài',         'strange; odd'),
    (3, '骑',       '騎',       'qi2',                'qí',             'to ride (an animal or bike); to sit astride'),
    (3, '起飞',     '起飛',     'qi3fei1',            'qǐfēi',          'take off (in an airplane); liftoff'),
    (3, '起来',     '起來',     'qi3lai5',            'qǐlai',          '(beginning or continuing an action); to rise; get up (from bed)'),
    (3, '清楚',     '清楚',     'qing1chu5',          'qīngchu',        'clear; distinct; be clear about'),
    (3, '请假',     '請假',     'qing3jia4',          'qǐngjià',        'to ask for time off'),
    (3, '秋',       '秋',       'qiu1',               'qiū',            'autumn; fall; harvest time'),
    (3, '裙子',     '裙子',     'qun2zi5',            'qúnzi',          'skirt'),
    (3, '然后',     '然后',     'ran2hou4',           'ránhòu',         'then; afterwards'),
    (3, '热情',     '熱情',     're4qing2',           'rèqíng',         'cordial; warm; enthusiastic'),
    (3, '认为',     '認為',     'ren4wei2',           'rènwéi',         'believe; think that'),
    (3, '认真',     '認真',     'ren4zhen1',          'rènzhēn',        'serious; earnest; take seriously'),
    (3, '容易',     '容易',     'rong2yi4',           'róngyì',         'easy; likely; liable (to)'),
    (3, '如果',     '如果',     'ru2guo3',            'rúguǒ',          'if; in the event that'),
    (3, '伞',       '傘',       'san3',               'sǎn',            'umbrella; parasol'),
    (3, '上网',     '上網',     'shang4wang3',        'shàngwǎng',      'to surf the web; to go online'),
    (3, '生气',     '生氣',     'sheng1qi4',          'shēngqì',        'angry; mad'),
    (3, '声音',     '聲音',     'sheng1yin1',         'shēngyīn',       'sound; voice'),
    (3, '世界',     '世界',     'shi4jie4',           'shìjiè',         'world'),
    (3, '试',       '試',       'shi4',               'shì',            'to try; to test; examination'),
    (3, '瘦',       '瘦',       'shou4',              'shòu',           'thin; tight; lean'),
    (3, '叔叔',     '叔叔',     'shu1shu5',           'shūshu',         '(informal) father''s younger brother; uncle'),
    (3, '舒服',     '舒服',     'shu1fu5',            'shūfu',          'comfortable; feeling well'),
    (3, '树',       '樹',       'shu4',               'shù',            'tree'),
    (3, '数学',     '數學',     'shu4xue2',           'shùxué',         'mathematics'),
    (3, '刷牙',     '刷牙',     'shua1ya2',           'shuāyá',         'brush one''s teeth'),
    (3, '双',       '雙',       'shuang1',            'shuāng',         'two; double; (mw for pairs)'),
    (3, '水平',     '水平',     'shui3ping2',         'shuǐpíng',       'level; standard; horizontal'),
    (3, '司机',     '司機',     'si1ji1',             'sījī',           'driver; chauffeur'),
    (3, '太阳',     '太陽',     'tai4yang2',          'tàiyáng',        'the sun'),
    (3, '特别',     '特別',     'te4bie2',            'tèbié',          'special; especially; particular'),
    (3, '疼',       '疼',       'teng2',              'téng',           'ache; sore; (it) hurts; love fondly'),
    (3, '提高',     '提高',     'ti2gao1',            'tígāo',          'to raise; heighten; improve'),
    (3, '体育',     '體育',     'ti3yu4',             'tǐyù',           'physical training; sports'),
    (3, '甜',       '甜',       'tian2',              'tián',           'sweet'),
    (3, '条',       '條',       'tiao2',              'tiáo',           'strip; (mw for long thin objects); item'),
    (3, '同事',     '同事',     'tong2shi4',          'tóngshì',        'colleague; co-worker'),
    (3, '同意',     '同意',     'tong2yi4',           'tóngyì',         'agree; to consent; approve'),
    (3, '头发',     '頭發',     'tou2fa5',            'tóufa',          'hair (on the head)'),
    (3, '突然',     '突然',     'tu1ran2',            'tūrán',          'sudden; abrupt'),
    (3, '图书馆',   '圖書館',   'tu2shu1guan3',       'túshūguǎn',      'library'),
    (3, '腿',       '腿',       'tui3',               'tuǐ',            'leg'),
    (3, '完成',     '完成',     'wan2cheng2',         'wánchéng',       'to complete; accomplish; to fulfill'),
    (3, '碗',       '碗',       'wan3',               'wǎn',            'bowl; cup'),
    (3, '万',       '萬',       'wan4',               'wàn',            'ten thousand'),
    (3, '忘记',     '忘記',     'wang4ji4',           'wàngjì',         'forget'),
    (3, '为',       '為',       'wei4',               'wèi',            'for; because of; to; for the sake of'),
    (3, '为了',     '為了',     'wei4le5',            'wèile',          'in order to; for the sake of; for the purpose of'),
    (3, '位',       '位',       'wei4',               'wèi',            'position; location; (polite mw for people)'),
    (3, '文化',     '文化',     'wen2hua4',           'wénhuà',         'culture; civilization'),
    (3, '西',       '西',       'xi1',                'xī',             'West (Kangxi radical 146)'),
    (3, '习惯',     '習慣',     'xi2guan4',           'xíguàn',         'habit; be accustomed to; usual practice'),
    (3, '洗手间',   '洗手間',   'xi3shou3jian1',      'xǐshǒujiān',     'toilet; lavatory; washroom'),
    (3, '洗澡',     '洗澡',     'xi3zao3',            'xǐzǎo',          'bathe; take a bath or shower; bath or shower'),
    (3, '夏',       '夏',       'xia4',               'xià',            'summer'),
    (3, '先',       '先',       'xian1',              'xiān',           'first; early; before'),
    (3, '相信',     '相信',     'xiang1xin4',         'xiāngxìn',       'believe (sb.); be convinced of'),
    (3, '香蕉',     '香蕉',     'xiang1jiao1',        'xiāngjiāo',      'banana'),
    (3, '向',       '向',       'xiang4',             'xiàng',          'direction; towards; to turn; to face'),
    (3, '像',       '像',       'xiang4',             'xiàng',          'be like; resemble; appearance; appear'),
    (3, '小心',     '小心',     'xiao3xin1',          'xiǎoxīn',        'be careful'),
    (3, '校长',     '校長',     'xiao4zhang3',        'xiàozhǎng',      'principal (of school, college or university); president; headmaster'),
    (3, '新闻',     '新聞',     'xin1wen2',           'xīnwén',         'news'),
    (3, '新鲜',     '新鮮',     'xin1xian1',          'xīnxiān',        'fresh (experience, food, etc.); new; novel'),
    (3, '信用卡',   '信用卡',   'xin4yong4ka3',       'xìnyòngkǎ',      'credit card'),
    (3, '行李箱',   '行李箱',   'xing2li3xiang1',     'xínglǐxiāng',    'trunk; suitcase'),
    (3, '熊猫',     '熊貓',     'xiong2mao1',         'xióngmāo',       'panda'),
    (3, '需要',     '需要',     'xu1yao4',            'xūyào',          'to need; to want; to demand'),
    (3, '选择',     '選擇',     'xuan3ze2',           'xuǎnzé',         'select; to pick; choose'),
    (3, '要求',     '要求',     'yao1qiu2',           'yāoqiú',         'to request; to demand; requirement'),
    (3, '爷爷',     '爺爺',     'ye2ye5',             'yéye',           '(informal) father''s father; paternal grandfather'),
    (3, '一般',     '一般',     'yi4ban1',            'yìbān',          'general; ordinary; common; same'),
    (3, '一边',     '一邊',     'yi4bian1',           'yìbiān',         'one side; on the one hand; at the same time'),
    (3, '一定',     '一定',     'yi2ding4',           'yídìng',         'surely; certainly; necessarily; definite'),
    (3, '一共',     '一共',     'yi2gong4',           'yígòng',         'altogether; in total'),
    (3, '一会儿',   '一會兒',   'yi2hui4r5',          'yíhuìr',         'a while; a moment'),
    (3, '一样',     '一樣',     'yi2yang4',           'yíyàng',         'the same; alike; equal to'),
    (3, '一直',     '一直',     'yi4zhi2',            'yìzhí',          'always; all along; straight (in a straight line)'),
    (3, '以前',     '以前',     'yi3qian2',           'yǐqián',         'before; formerly; previous'),
    (3, '音乐',     '音樂',     'yin1yue4',           'yīnyuè',         'music'),
    (3, '银行',     '銀行',     'yin2hang2',          'yínháng',        'bank'),
    (3, '饮料',     '飲料',     'yin3liao4',          'yǐnliào',        'beverage; drink'),
    (3, '应该',     '應該',     'ying1gai1',          'yīnggāi',        'should; ought to; must'),
    (3, '影响',     '影響',     'ying3xiang3',        'yǐngxiǎng',      'influence; affect; effect'),
    (3, '用',       '用',       'yong4',              'yòng',           'to use (Kangxi radical 101)'),
    (3, '游戏',     '游戲',     'you2xi4',            'yóuxì',          'game; play; recreation'),
    (3, '有名',     '有名',     'you3ming2',          'yǒumíng',        'famous; well-known'),
    (3, '又',       '又',       'you4',               'yòu',            '(once) again; also; both (Kangxi radical 29)'),
    (3, '遇到',     '遇到',     'yu4dao4',            'yùdào',          'to meet; run into; come across'),
    (3, '元',       '元',       'yuan2',              'yuán',           'Chinese monetary unit; dollar; first; principal'),
    (3, '愿意',     '願意',     'yuan4yi4',           'yuànyì',         'be willing; want to; be ready'),
    (3, '月亮',     '月亮',     'yue4liang5',         'yuèliang',       'the moon'),
    (3, '越',       '越',       'yue4',               'yuè',            'even more; the more; exceed'),
    (3, '站',       '站',       'zhan4',              'zhàn',           'stand; a station; be on one''s feet; service center'),
    (3, '张',       '張',       'zhang1',             'zhāng',          '(mw for flat objects); to spread out; (common surname)'),
    (3, '长',       '長',       'chang2, zhang3',     'cháng, zhǎng',   'long; length | grow; chief (Kangxi radical 168'),
    (3, '着急',     '著急',     'zhao2ji2',           'zháojí',         'to worry; feel anxious'),
    (3, '照顾',     '照顧',     'zhao4gu5',           'zhàogu',         'take care of; look after; give consideration'),
    (3, '照片',     '照片',     'zhao4pian4',         'zhàopiàn',       'picture; photograph'),
    (3, '照相机',   '照相機',   'zhao4xiang4ji1',     'zhàoxiàngjī',    'camera'),
    (3, '只',       '隻',       'zhi1, zhi3',         'zhī, zhǐ',       'but; only; merely; just | (mw for birds and certain animals)'),
    (3, '只有',     '隻有',     'zhi3you3',           'zhǐyǒu',         'only'),
    (3, '才',       '才',       'cai2',               'cái',            'ability; talent; just now; not until'),
    (3, '中间',     '中間',     'zhong1jian1',        'zhōngjiān',      'center; middle; between; among'),
    (3, '中文',     '中文',     'Zhong1wen2',         'Zhōngwén',       'Chinese (language)'),
    (3, '终于',     '終於',     'zhong1yu2',          'zhōngyú',        'at last; in the end; finally'),
    (3, '种',       '種',       'zhong3',             'zhǒng',          'type; breed; race; seed'),
    (3, '重要',     '重要',     'zhong4yao4',         'zhòngyào',       'important; significant; major'),
    (3, '周末',     '周末',     'zhou1mo4',           'zhōumò',         'weekend'),
    (3, '主要',     '主要',     'zhu3yao4',           'zhǔyào',         'main; principal; major'),
    (3, '注意',     '注意',     'zhu4yi4',            'zhùyì',          'pay attention to; take notice of; be careful'),
    (3, '自己',     '自己',     'zi4ji3',             'zìjǐ',           'oneself; self'),
    (3, '自行车',   '自行車',   'zi4xing2che1',       'zìxíngchē',      'bike; bicycle'),
    (3, '总是',     '總是',     'zong3shi4',          'zǒngshì',        'always; eventually'),
    (3, '嘴',       '嘴',       'zui3',               'zuǐ',            'mouth'),
    (3, '最后',     '最后',     'zui4hou4',           'zuìhòu',         'last; final; ultimately'),
    (3, '最近',     '最近',     'zui4jin4',           'zuìjìn',         'recently; lately; these days'),
    (3, '作业',     '作業',     'zuo4ye4',            'zuòyè',          'school assignment; homework; task')
;

COMMIT TRANSACTION;
