BEGIN TRANSACTION;

INSERT INTO vocabulary (
    hsk_level,
    hans,
    hant,
    pinyin_input,
    pinyin_display,
    definition
)
VALUES
    (4, '爱情',     '愛情',     'ai4qing2',         'àiqíng',        '(romantic) love'),
    (4, '安排',     '安排',     'an1pai2',          'ānpái',         'arrange; to plan'),
    (4, '安全',     '安全',     'an1quan2',         'ānquán',        'safe; safety; secure; security'),
    (4, '按时',     '按時',     'an4shi2',          'ànshí',         'on time; on schedule'),
    (4, '按照',     '按照',     'an4zhao4',         'ànzhào',        'according to; in accordance with; in light of'),
    (4, '百分之',   '百分之',   'bai3fen1zhi1',     'bǎifēnzhī',     'percent'),
    (4, '棒',       '棒',       'bang4',            'bàng',          'stick; club; good; excellent'),
    (4, '包子',     '包子',     'bao1zi',           'bāozi',         'steamed stuffed bun'),
    (4, '保护',     '保護',     'bao3hu4',          'bǎohù',         'to protect; to defend'),
    (4, '保证',     '保證',     'bao3zheng4',       'bǎozhèng',      'to guarantee; ensure'),
    (4, '报名',     '報名',     'bao4 ming2',       'bào míng',      'sign up; apply'),
    (4, '抱',       '抱',       'bao4',             'bào',           'to hold; to hug; carry in one''s arms; to cradle'),
    (4, '抱歉',     '抱歉',     'bao4qian4',        'bàoqiàn',       'be sorry; feel apologetic; to regret'),
    (4, '倍',       '倍',       'bei4',             'bèi',           '(two, three, etc)-fold; times (multiplier)'),
    (4, '本来',     '本來',     'ben3lai2',         'běnlái',        'originally; at first'),
    (4, '笨',       '笨',       'ben4',             'bèn',           'stupid; foolish; silly; dumb; clumsy'),
    (4, '比如',     '比如',     'bi3ru2',           'bǐrú',          'for example; for instance; such as'),
    (4, '毕业',     '畢業',     'bi4 ye4',          'bì yè',         'to graduate; to finish school'),
    (4, '遍',       '遍',       'bian4',            'biàn',          'a time; everywhere; turn; (mw for times or turns)'),
    (4, '标准',     '標准',     'biao1zhun3',       'biāozhǔn',      '(an official) standard; norm; criterion'),
    (4, '表格',     '表格',     'biao3ge2',         'biǎogé',        'form (document)'),
    (4, '表示',     '表示',     'biao3shi4',        'biǎoshì',       'express; show; indicate'),
    (4, '表演',     '表演',     'biao3yan3',        'biǎoyǎn',       'perform; to play'),
    (4, '表扬',     '表揚',     'biao3yang2',       'biǎoyáng',      'to praise; commend'),
    (4, '饼干',     '餅幹',     'bing3gan1',        'bǐnggān',       'biscuit; cracker; cookie'),
    (4, '并且',     '並且',     'bing4qie3',        'bìngqiě',       'and; besides; moreover'),
    (4, '博士',     '博士',     'bo2shi4',          'bóshì',         'doctor; PhD'),
    (4, '不得不',   '不得不',   'bu4 de2 bu4',      'bù dé bù',      'have to; have no choice but to; cannot but'),
    (4, '不管',     '不管',     'bu4guan3',         'bùguǎn',        'no matter (what, how, etc.); regardless of'),
    (4, '不过',     '不過',     'bu2guo4',          'búguò',         'only; merely; but; however'),
    (4, '不仅',     '不僅',     'bu4jin3',          'bùjǐn',         'not only; not just'),
    (4, '部分',     '部分',     'bu4fen',           'bùfen',         'part; share; section'),
    (4, '擦',       '擦',       'ca1',              'cā',            'to wipe; to rub; to polish'),
    (4, '猜',       '猜',       'cai1',             'cāi',           'to guess'),
    (4, '材料',     '材料',     'cai2liao4',        'cáiliào',       'material'),
    (4, '参观',     '參觀',     'cang1uan1',        'cānguān',       'to visit (a place, such as a tourist spot); inspect'),
    (4, '餐厅',     '餐廳',     'can1ting1',        'cāntīng',       'dining hall; cafeteria; restaurant'),
    (4, '厕所',     '廁所',     'ce4suo3',          'cèsuǒ',         'bathroom; toilet; lavatory'),
    (4, '差不多',   '差不多',   'cha4buduo1',       'chàbuduō',      'almost; about the same'),
    (4, '长城',     '長城',     'chang2cheng2',     'chángchéng',    'the Great Wall'),
    (4, '长江',     '長江',     'Chang2jiang1',     'Chángjiāng',    'the Yangtze River; the Changjiang River'),
    (4, '尝',       '嘗',       'chang2',           'cháng',         'to taste; flavor; (past tense marker)'),
    (4, '场',       '場',       'chang3',           'chǎng',         'courtyard; place; field; (mw for games, performances, etc.)'),
    (4, '超过',     '超過',     'chao1guo4',        'chāoguò',       'surpass; exceed; outstrip'),
    (4, '成功',     '成功',     'cheng2gong1',      'chénggōng',     'success; to succeed'),
    (4, '成为',     '成爲',     'cheng2wei2',       'chéngwéi',      'become; turn into'),
    (4, '诚实',     '誠實',     'cheng2shi2',       'chéngshí',      'honest; honorable'),
    (4, '乘坐',     '乘坐',     'cheng2zuo4',       'chéngzuò',      'ride; get into (a vehicle)'),
    (4, '吃惊',     '吃驚',     'chi1 jing1',       'chī jīng',      'be startled; be shocked; be amazed'),
    (4, '重新',     '重新',     'chong2xin1',       'chóngxīn',      'again; anew; once more'),
    (4, '抽烟',     '抽煙',     'chou1yan1',        'chōuyān',       'to smoke (a cigarette, pipe, etc.)'),
    (4, '出差',     '出差',     'chu1 chai1',       'chū chāi',      'go on a business trip'),
    (4, '出发',     '出發',     'chu1fa1',          'chūfā',         'start out; set off'),
    (4, '出生',     '出生',     'chu1sheng1',       'chūshēng',      'be born'),
    (4, '出现',     '出現',     'chu1xian4',        'chūxiàn',       'appear; arise; emerge'),
    (4, '厨房',     '廚房',     'chu2fang2',        'chúfáng',       'kitchen'),
    (4, '传真',     '傳真',     'chuan2zhen1',      'chuánzhēn',     'fax; facsimile'),
    (4, '窗户',     '窗戶',     'chuang1hu',        'chuānghu',      'window'),
    (4, '词语',     '詞語',     'ci2yu3',           'cíyǔ',          'words and expressions; terms'),
    (4, '从来',     '從來',     'cong2lai2',        'cónglái',       'always; at all times'),
    (4, '粗心',     '粗心',     'cu1xin1',          'cūxīn',         'careless; inadvertent; negligent'),
    (4, '存',       '存',       'cun2',             'cún',           'exist; to deposit; to store'),
    (4, '错误',     '錯誤',     'cuo4wu4',          'cuòwù',         'error; mistake; mistaken'),
    (4, '答案',     '答案',     'da2an4',          'dáàn',         'answer; solution'),
    (4, '打扮',     '打扮',     'da3ban',           'dǎban',         'dress up; put on make up'),
    (4, '打扰',     '打擾',     'da3rao3',          'dǎrǎo',         'disturb'),
    (4, '打印',     '打印',     'da3yin4',          'dǎyìn',         'to print'),
    (4, '打招呼',   '打招呼',   'da3zhao1hu',       'dǎzhāohu',      'notify; greet; inform'),
    (4, '打折',     '打折',     'da3zhe2',          'dǎzhé',         'sell at a discount'),
    (4, '打针',     '打針',     'da3zhen1',         'dǎzhēn',        'inject; get a shot'),
    (4, '大概',     '大概',     'da4gai4',          'dàgài',         'probably; roughly; approximate'),
    (4, '大使馆',   '大使館',   'da4shi3guan3',     'dàshǐguǎn',     'embassy'),
    (4, '大约',     '大約',     'da4yue1',          'dàyuē',         'approximately; about'),
    (4, '大夫',     '大夫',     'dai4fu',           'dàifu',         'doctor; physician'),
    (4, '戴',       '戴',       'dai4',             'dài',           'put on; to wear; to respect'),
    (4, '当',       '當',       'dang1',            'dāng',          'should; act as; work as; manage; match; (sound of bells)'),
    (4, '当时',     '當時',     'dang1shi2',        'dāngshí',       'then; at that time; while'),
    (4, '刀',       '刀',       'dao1',             'dāo',           'knife; blade (Kangxi radical 18)'),
    (4, '导游',     '導遊',     'dao3you2',         'dǎoyóu',        'tour guide'),
    (4, '到处',     '到處',     'dao4chu4',         'dàochù',        'everywhere; in all places; all over'),
    (4, '到底',     '到底',     'dao4 di3',         'dào dǐ',        'after all; in the end (used in a question)'),
    (4, '倒',       '倒',       'dao3, dao4',       'dǎo, dào',      'to collapse; to fall; fail; to exchange | to pour; contrary to expectations'),
    (4, '道歉',     '道歉',     'dao4qian4',        'dàoqiàn',       'apologize; make an apology'),
    (4, '得意',     '得意',     'de2yi4',           'déyì',          'proud of oneself; complacent'),
    (4, '得',       '得',       'de',               'de',            '(complement particle)'),
    (4, '登机牌',   '登機牌',   'deng1ji1pai2',     'dēngjīpái',     'boarding pass'),
    (4, '等',       '等',       'deng3',            'děng',          'to wait; rank; equal; etc.'),
    (4, '低',       '低',       'di1',              'dī',            'low; to lower (one''s head); droop'),
    (4, '底',       '底',       'di3',              'dǐ',            'bottom; background; base'),
    (4, '地点',     '地點',     'di4dian3',         'dìdiǎn',        'place; site; location'),
    (4, '地球',     '地球',     'di4qiu2',          'dìqiú',         'the Earth; planet'),
    (4, '地址',     '地址',     'di4zhi3',          'dìzhǐ',         'address'),
    (4, '调查',     '調查',     'diao4cha2',        'diàochá',       'investigate; survey; inquiry'),
    (4, '掉',       '掉',       'diao4',            'diào',          'to drop; to fall'),
    (4, '丢',       '丟',       'diu1',             'diū',           'lose (something); throw; put aside'),
    (4, '动作',     '動作',     'dong4zuo4',        'dòngzuò',       'movement; motion; action'),
    (4, '堵车',     '堵車',     'du3che1',          'dǔchē',         'traffic jam'),
    (4, '肚子',     '肚子',     'du4zi',            'dùzi',          'belly; abdomen; stomach'),
    (4, '短信',     '短信',     'duan3xin4',        'duǎnxìn',       'text message; SMS'),
    (4, '对话',     '對話',     'dui4hua4',         'duìhuà',        'dialogue; conversation'),
    (4, '对面',     '對面',     'dui4mian4',        'duìmiàn',       'opposite; across from; the other side'),
    (4, '对于',     '對于',     'dui4yu2',          'duìyú',         'regarding; as far as sth. is concerned; with regards to; for'),
    (4, '儿童',     '兒童',     'er2tong2',         'értóng',        'child; children'),
    (4, '而',       '而',       'er2',              'ér',            'and; but; yet; while (Kangxi radical 126)'),
    (4, '发生',     '發生',     'fa1sheng1',        'fāshēng',       'happen; occur; take place'),
    (4, '发展',     '發展',     'fa1zhan3',         'fāzhǎn',        'develop; development; growth'),
    (4, '法律',     '法律',     'fa3lü4',           'fǎlǜ',          'law; statute'),
    (4, '翻译',     '翻譯',     'fan1yi4',          'fānyì',         'translate; translation; interpret'),
    (4, '烦恼',     '煩惱',     'fan2nao3',         'fánnǎo',        'worried; vexed'),
    (4, '反对',     '反對',     'fan3dui4',         'fǎnduì',        'oppose; fight against'),
    (4, '方法',     '方法',     'fang1fa3',         'fāngfǎ',        'method; way; means'),
    (4, '方面',     '方面',     'fang1mian4',       'fāngmiàn',      'aspect; field; side'),
    (4, '方向',     '方向',     'fang1xiang4',      'fāngxiàng',     'direction; orientation'),
    (4, '房东',     '房東',     'fang2dong1',       'fángdōng',      'landlord'),
    (4, '放弃',     '放棄',     'fang4qi4',         'fàngqì',        'abandon; renounce; give up'),
    (4, '放暑假',   '放暑假',   'fang4 shu3jia4',   'fàng shǔjià',   'have summer vacation'),
    (4, '放松',     '放松',     'fang4song1',       'fàngsōng',      'relax; loosen; slacken'),
    (4, '份',       '份',       'fen4',             'fèn',           'part; portion; (mw for documents, papers, jobs, etc.)'),
    (4, '丰富',     '豐富',     'feng1fu4',         'fēngfù',        'rich; enrich; abundant; plentiful'),
    (4, '否则',     '否則',     'fou3ze2',          'fǒuzé',         'if not; otherwise; or else'),
    (4, '符合',     '符合',     'fu2he2',           'fúhé',          'in keeping with; in accordance with; conform'),
    (4, '父亲',     '父親',     'fu4qin',           'fùqin',         'father'),
    (4, '付款',     '付款',     'fu4 kuan3',        'fù kuǎn',       'to pay'),
    (4, '负责',     '負責',     'fu4ze2',           'fùzé',          'responsible for (something); in charge of'),
    (4, '复印',     '複印',     'fu4yin4',          'fùyìn',         'photocopy; duplicate'),
    (4, '复杂',     '複雜',     'fu4za2',           'fùzá',          'complicated; complex'),
    (4, '富',       '富',       'fu4',              'fù',            'wealthy'),
    (4, '改变',     '改變',     'gai3bian4',        'gǎibiàn',       'to change; alter; to transform'),
    (4, '干杯',     '幹杯',     'gan1 bei1',        'gān bēi',       'to drink a toast; cheers!; bottoms up!'),
    (4, '赶',       '趕',       'gan3',             'gǎn',           'catch up; overtake; drive away'),
    (4, '敢',       '敢',       'gan3',             'gǎn',           'to dare'),
    (4, '感动',     '感動',     'gan3dong4',        'gǎndòng',       'be moved; to touch emotionally'),
    (4, '感觉',     '感覺',     'gan3jue2',         'gǎnjué',        'to feel; become aware of; feeling'),
    (4, '感情',     '感情',     'gan3qing2',        'gǎnqíng',       'feeling; emotion; sensation'),
    (4, '感谢',     '感謝',     'gan3xie4',         'gǎnxiè',        'thank; be grateful'),
    (4, '干',       '幹',       'gan1',             'gān',           'to concern; shield; dry; clean (Kangxi radical 51)'),
    (4, '刚',       '剛',       'gang1',            'gāng',          'just (indicating the immediate past); recently; firm'),
    (4, '高速公路', '高速公路', 'gao1su4 gong1lu4', 'gāosù gōnglù',  'highway'),
    (4, '胳膊',     '胳膊',     'ge1bo',            'gēbo',          'arm'),
    (4, '各',       '各',       'ge4',              'gè',            'each; every'),
    (4, '工资',     '工資',     'gong1zi1',         'gōngzī',        'wages; pay; earnings; salary'),
    (4, '公里',     '公裏',     'gong1li3',         'gōnglǐ',        'kilometer'),
    (4, '功夫',     '功夫',     'gong1fu',          'gōngfu',        'kung fu; skill; art; labor'),
    (4, '共同',     '共同',     'gong4tong2',       'gòngtóng',      'together; common; joint'),
    (4, '购物',     '購物',     'gou4wu4',          'gòuwù',         'go shopping; buy goods'),
    (4, '够',       '夠',       'gou4',             'gòu',           'enough; to reach'),
    (4, '估计',     '估計',     'gu1ji4',           'gūjì',          'appraise; estimate'),
    (4, '鼓励',     '鼓勵',     'gu3li4',           'gǔlì',          'encourage; inspire'),
    (4, '故意',     '故意',     'gu4yi4',           'gùyì',          'deliberately; intentional; on purpose'),
    (4, '顾客',     '顧客',     'gu4ke4',           'gùkè',          'customer; client'),
    (4, '挂',       '挂',       'gua4',             'guà',           'hang; put up; suspend'),
    (4, '关键',     '關鍵',     'guan1jian4',       'guānjiàn',      'crucial; key; pivotal'),
    (4, '观众',     '觀衆',     'guan1zhong4',      'guānzhòng',     'spectator; audience'),
    (4, '管理',     '管理',     'guan3li3',         'guǎnlǐ',        'supervise; manage'),
    (4, '光',       '光',       'guang1',           'guāng',         'light; ray; bright; only; merely; used up'),
    (4, '广播',     '廣播',     'guang3bo1',        'guǎngbō',       'broadcast; on the air'),
    (4, '广告',     '廣告',     'guang3gao4',       'guǎnggào',      'advertisement; a commercial'),
    (4, '逛',       '逛',       'guang4',           'guàng',         'to stroll; to visit; go window shopping'),
    (4, '规定',     '規定',     'gui1ding4',        'guīdìng',       'regulation; stipulate; fix; set'),
    (4, '国籍',     '國籍',     'guo2ji2',          'guójí',         'nationality'),
    (4, '国际',     '國際',     'guo2ji4',          'guójì',         'international'),
    (4, '果汁',     '果汁',     'guo3zhi1',         'guǒzhī',        'fruit juice'),
    (4, '过程',     '過程',     'guo4cheng2',       'guòchéng',      'course of events; process'),
    (4, '海洋',     '海洋',     'hai3yang2',        'hǎiyáng',       'ocean'),
    (4, '害羞',     '害羞',     'hai4 xiu1',        'hài xiū',       'blush; shy'),
    (4, '寒假',     '寒假',     'han2jia4',         'hánjià',        'winter vacation'),
    (4, '汗',       '汗',       'han4',             'hàn',           'sweat; perspiration; Khan'),
    (4, '航班',     '航班',     'hang2ban1',        'hángbān',       'scheduled flight; flight number'),
    (4, '好处',     '好處',     'hao3chu',          'hǎochu',        'benefit; advantage'),
    (4, '好像',     '好像',     'hao3xiang4',       'hǎoxiàng',      'as if; seem to be'),
    (4, '号码',     '號碼',     'hao4ma3',          'hàomǎ',         'number'),
    (4, '合格',     '合格',     'he2ge2',           'hégé',          'qualified; up to standard'),
    (4, '合适',     '合適',     'he2shi4',          'héshì',         'suitable; proper; appropriate'),
    (4, '盒子',     '盒子',     'he2zi',            'hézi',          'box'),
    (4, '后悔',     '後悔',     'hou4hui3',         'hòuhuǐ',        'to regret; repent'),
    (4, '厚',       '厚',       'hou4',             'hòu',           'thick (for flat things); generous'),
    (4, '互联网',   '互聯網',   'Hu4lian2wang3',    'Hùliánwǎng',    'Internet'),
    (4, '互相',     '互相',     'hu4xiang1',        'hùxiāng',       'mutually; with each other'),
    (4, '护士',     '護士',     'hu4shi',           'hùshi',         'nurse'),
    (4, '怀疑',     '懷疑',     'huai2yi2',         'huáiyí',        'doubt; to suspect; be skeptical'),
    (4, '回忆',     '回憶',     'hui2yi4',          'huíyì',         'to recall; recollect'),
    (4, '活动',     '活動',     'huo2dong4',        'huódòng',       'activity; exercise; move about'),
    (4, '活泼',     '活潑',     'huo2po',           'huópo',         'lively; vivacious'),
    (4, '火',       '火',       'huo3',             'huǒ',           'fire (Kangxi radical 86)'),
    (4, '获得',     '獲得',     'huo4de2',          'huòdé',         'obtain; acquire; to gain'),
    (4, '积极',     '積極',     'ji1ji2',           'jījí',          'active; positive; energetic'),
    (4, '积累',     '積累',     'ji1lei3',          'jīlěi',         'accumulate; accumulation'),
    (4, '基础',     '基礎',     'ji1chu3',          'jīchǔ',         'base; foundation'),
    (4, '激动',     '激動',     'ji1dong4',         'jīdòng',        'excite; agitate'),
    (4, '及时',     '及時',     'ji2shi2',          'jíshí',         'timely; in time; promptly; without delay'),
    (4, '即使',     '即使',     'ji2shi3',          'jíshǐ',         'even if; even though'),
    (4, '计划',     '計劃',     'ji4hua4',          'jìhuà',         'plan; project'),
    (4, '记者',     '記者',     'ji4zhe3',          'jìzhě',         'reporter; journalist'),
    (4, '技术',     '技術',     'ji4shu4',          'jìshù',         'technology; technique; skill'),
    (4, '既然',     '既然',     'ji4ran2',          'jìrán',         'since; given that; now that'),
    (4, '继续',     '繼續',     'ji4xu4',           'jìxù',          'to continue; to go on; to proceed'),
    (4, '寄',       '寄',       'ji4',              'jì',            'send by mail'),
    (4, '加班',     '加班',     'jia1 ban1',        'jiā bān',       'work overtime'),
    (4, '加油站',   '加油站',   'jia1you2zhan4',    'jiāyóuzhàn',    'gas station'),
    (4, '家具',     '家具',     'jia1ju4',          'jiājù',         'furniture'),
    (4, '假',       '假',       'jia3, jia4',       'jiǎ, jià',      'fake; if; borrow | vacation; holiday'),
    (4, '价格',     '價格',     'jia4ge2',          'jiàgé',         'price'),
    (4, '坚持',     '堅持',     'jian1chi2',        'jiānchí',       'persist in; persevere'),
    (4, '减肥',     '減肥',     'jian3fei2',        'jiǎnféi',       'go on a diet; lose weight'),
    (4, '减少',     '減少',     'jian3shao3',       'jiǎnshǎo',      'reduce; to decrease'),
    (4, '建议',     '建議',     'jian4yi4',         'jiànyì',        'to propose; to suggest; recommend'),
    (4, '将来',     '將來',     'jiang1lai2',       'jiānglái',      'the future'),
    (4, '奖金',     '獎金',     'jiang3jin1',       'jiǎngjīn',      'bonus'),
    (4, '降低',     '降低',     'jiang4di1',        'jiàngdī',       'reduce; to lower; to drop'),
    (4, '降落',     '降落',     'jiang4luo4',       'jiàngluò',      'descend; to land; put down'),
    (4, '交',       '交',       'jiao1',            'jiāo',          'deliver; turn over; intersect; to pay (money); friendship'),
    (4, '交流',     '交流',     'jiao1liu2',        'jiāoliú',       'communicate; exchange; give and take; interaction; to alternate'),
    (4, '交通',     '交通',     'jiao1tong1',       'jiāotōng',      'traffic; transportation'),
    (4, '郊区',     '郊區',     'jiao1qu1',         'jiāoqū',        'suburbs; outskirts'),
    (4, '骄傲',     '驕傲',     'jiao1ao4',        'jiāoào',       'proud; arrogant; conceited; take pride in'),
    (4, '饺子',     '餃子',     'jiao3zi',          'jiǎozi',        'dumpling; potsticker'),
    (4, '教授',     '教授',     'jiao4shou4',       'jiàoshòu',      'professor; instruct; to lecture'),
    (4, '教育',     '教育',     'jiao4yu4',         'jiàoyù',        'education'),
    (4, '接受',     '接受',     'jie1shou4',        'jiēshòu',       'accept; receive (honors, etc.)'),
    (4, '接着',     '接著',     'jie1zhe',          'jiēzhe',        'continue; carry on; to catch; follow'),
    (4, '节',       '節',       'jie2',             'jié',           'section; part; festival; moral integrity; save; (mw for class periods)'),
    (4, '节约',     '節約',     'jie2yue1',         'jiéyuē',        'frugal; to save'),
    (4, '结果',     '結果',     'jie2guo3',         'jiéguǒ',        'result; outcome; finally'),
    (4, '解释',     '解釋',     'jie3shi4',         'jiěshì',        'to explain'),
    (4, '尽管',     '盡管',     'jing3uan3',        'jǐnguǎn',       'despite; although; even though | freely; without hesitation'),
    (4, '紧张',     '緊張',     'jin3zhang1',       'jǐnzhāng',      'nervous; tension; strain'),
    (4, '进行',     '進行',     'jin4xing2',        'jìnxíng',       'carry on; carry out; undertake'),
    (4, '禁止',     '禁止',     'jin4zhi3',         'jìnzhǐ',        'to ban; prohibit'),
    (4, '京剧',     '京劇',     'jing1ju4',         'jīngjù',        'Beijing Opera'),
    (4, '经济',     '經濟',     'jing1ji4',         'jīngjì',        'economy; economic'),
    (4, '经历',     '經曆',     'jing1li4',         'jīnglì',        'undergo; to experience'),
    (4, '经验',     '經驗',     'jing1yan4',        'jīngyàn',       'experience'),
    (4, '精彩',     '精彩',     'jing1cai3',        'jīngcǎi',       'brilliant; spectacular; wonderful'),
    (4, '景色',     '景色',     'jing3se4',         'jǐngsè',        'scenery; landscape; scene; view'),
    (4, '警察',     '警察',     'jing3cha2',        'jǐngchá',       'police'),
    (4, '竞争',     '競爭',     'jing4zheng1',      'jìngzhēng',     'compete'),
    (4, '竟然',     '竟然',     'jing4ran2',        'jìngrán',       'unexpectedly; to one''s surprise; go so far as to'),
    (4, '镜子',     '鏡子',     'jing4zi',          'jìngzi',        'mirror'),
    (4, '究竟',     '究竟',     'jiu1jing4',        'jiūjìng',       'after all; when all is said and done; actually'),
    (4, '举',       '舉',       'ju3',              'jǔ',            'lift; raise; cite'),
    (4, '举办',     '舉辦',     'ju3ban4',          'jǔbàn',         'to conduct; to hold'),
    (4, '举行',     '舉行',     'ju3xing2',         'jǔxíng',        'convene; to hold (a meeting, ceremony, etc.)'),
    (4, '拒绝',     '拒絕',     'ju4jue2',          'jùjué',         'to refuse; to decline; to reject'),
    (4, '距离',     '距離',     'ju4li2',           'jùlí',          'distance; be apart; away from'),
    (4, '聚会',     '聚會',     'ju4hui4',          'jùhuì',         'hold a meeting; get together; a party'),
    (4, '开玩笑',   '開玩笑',   'kai1 wan2xiao4',   'kāi wánxiào',   'joke; play a joke; make fun of'),
    (4, '开心',     '開心',     'kai1xin1',         'kāixīn',        'feel happy; have a great time; make fun of somebody'),
    (4, '看法',     '看法',     'kan4fa3',          'kànfǎ',         'point of view; opinion'),
    (4, '考虑',     '考慮',     'kao3lü4',          'kǎolǜ',         'think over; consider'),
    (4, '烤鸭',     '烤鴨',     'kao3ya1',          'kǎoyā',         'roast duck'),
    (4, '科学',     '科學',     'ke1xue2',          'kēxué',         'science; scientific knowledge'),
    (4, '棵',       '棵',       'ke1',              'kē',            '(mw for plants)'),
    (4, '咳嗽',     '咳嗽',     'ke2sou',           'késou',         'to cough'),
    (4, '可怜',     '可憐',     'ke3lian2',         'kělián',        'pitiful; poor; pathetic'),
    (4, '可是',     '可是',     'ke3shi4',          'kěshì',         'but; however'),
    (4, '可惜',     '可惜',     'ke3xi1',           'kěxī',          'it''s a pity; regrettable; too bad'),
    (4, '客厅',     '客廳',     'ke4ting1',         'kètīng',        'living room; parlor'),
    (4, '肯定',     '肯定',     'ken3ding4',        'kěndìng',       'sure; definite; affirm; approve'),
    (4, '空',       '空',       'kong1, kong4',     'kōng, kòng',    'empty; sky | leave blank; leisure'),
    (4, '空气',     '空氣',     'kong1qi4',         'kōngqì',        'air'),
    (4, '恐怕',     '恐怕',     'kong3pa4',         'kǒngpà',        'be afraid; to fear; I''m afraid that...'),
    (4, '苦',       '苦',       'ku3',              'kǔ',            'bitter; miserable'),
    (4, '矿泉水',   '礦泉水',   'kuang4quan2shui3', 'kuàngquánshuǐ', 'mineral water'),
    (4, '困',       '困',       'kun4',             'kùn',           'sleepy; surround; hard-pressed'),
    (4, '困难',     '困難',     'kun4nan',          'kùnnan',        'difficulty; difficult; problem'),
    (4, '垃圾桶',   '垃圾桶',   'la1ji1tong3',      'lājītǒng',      'garbage can'),
    (4, '拉',       '拉',       'la1',              'lā',            'to pull; to play (string instruments); to drag'),
    (4, '辣',       '辣',       'la4',              'là',            'hot (spicy)'),
    (4, '来不及',   '來不及',   'lai2 bu ji2',      'lái bu jí',     'there''s not enough time (to do something); it''s too late'),
    (4, '来得及',   '來得及',   'lai2 de ji2',      'lái de jí',     'there''s still time'),
    (4, '来自',     '來自',     'lai2zi4',          'láizì',         'come from (a place)'),
    (4, '懒',       '懶',       'lan3',             'lǎn',           'lazy'),
    (4, '浪费',     '浪費',     'lang4fei4',        'làngfèi',       'to waste; squander'),
    (4, '浪漫',     '浪漫',     'lang4man4',        'làngmàn',       'romantic'),
    (4, '老虎',     '老虎',     'lao3hu3',          'lǎohǔ',         'tiger'),
    (4, '冷静',     '冷靜',     'leng3jing4',       'lěngjìng',      'calm; cool-headed; sober'),
    (4, '礼拜天',   '禮拜天',   'li3bai4tian1',     'lǐbàitiān',     'Sunday'),
    (4, '礼貌',     '禮貌',     'li3mao4',          'lǐmào',         'courtesy; politeness; manners'),
    (4, '理发',     '理發',     'li3fa4',           'lǐfà',          'a barber, hairdressing; haircut'),
    (4, '理解',     '理解',     'li3jie3',          'lǐjiě',         'comprehend; understand'),
    (4, '理想',     '理想',     'li3xiang3',        'lǐxiǎng',       'ideal'),
    (4, '力气',     '力氣',     'li4qi',            'lìqi',          'physical strength; effort'),
    (4, '厉害',     '厲害',     'li4hai',           'lìhai',         'terrible; formidable; fierce; cool; awesome'),
    (4, '例如',     '例如',     'li4ru2',           'lìrú',          'for example; for instance'),
    (4, '俩',       '倆',       'liang3',           'liǎng',         '(colloquial) two (people)'),
    (4, '连',       '連',       'lian2',            'lián',          'even; including; join'),
    (4, '联系',     '聯系',     'lian2xi4',         'liánxì',        'integrate; link; connection; contact'),
    (4, '凉快',     '涼快',     'liang2kuai',       'liángkuai',     'nice and cool; pleasantly cool'),
    (4, '零钱',     '零錢',     'ling2qian2',       'língqián',      'small change (of money)'),
    (4, '另外',     '另外',     'ling4wai4',        'lìngwài',       'another; in addition; besides'),
    (4, '留',       '留',       'liu2',             'liú',           'to leave (behind, a message); to retain; to stay'),
    (4, '流利',     '流利',     'liu2li4',          'liúlì',         'fluent'),
    (4, '流行',     '流行',     'liu2xing2',        'liúxíng',       'spread; prevalent; be popular'),
    (4, '旅行',     '旅行',     'lü3xing2',         'lǚxíng',        'travel'),
    (4, '律师',     '律師',     'lü4shi1',          'lǜshī',         'lawyer'),
    (4, '乱',       '亂',       'luan4',            'luàn',          'disorder; confusion; arbitrarily'),
    (4, '麻烦',     '麻煩',     'ma2fan',           'máfan',         'trouble (someone); troubling; bothersome'),
    (4, '马虎',     '馬虎',     'ma3hu',            'mǎhu',          'careless; sloppy; casual'),
    (4, '满',       '滿',       'man3',             'mǎn',           'full; abbreviation for Manchurian'),
    (4, '毛',       '毛',       'mao2',             'máo',           'hair; fur; feather; dime (Kangxi radical 82)'),
    (4, '毛巾',     '毛巾',     'mao2jin1',         'máojīn',        'towel; washcloth'),
    (4, '美丽',     '美麗',     'mei3li4',          'měilì',         'beautiful'),
    (4, '梦',       '夢',       'meng4',            'mèng',          'to dream'),
    (4, '迷路',     '迷路',     'mi2lu4',           'mílù',          'to get lost'),
    (4, '密码',     '密碼',     'mi4ma3',           'mìmǎ',          'password; secret code'),
    (4, '免费',     '免費',     'mian3 fei4',       'miǎn fèi',      'free (of charge); no cost'),
    (4, '秒',       '秒',       'miao3',            'miǎo',          'second (unit of time or angle)'),
    (4, '民族',     '民族',     'min2zu2',          'mínzú',         'nationality; ethnic group'),
    (4, '母亲',     '母親',     'mu3qin',           'mǔqin',         'mother'),
    (4, '目的',     '目的',     'mu4di4',           'mùdì',          'purpose; aim; goal'),
    (4, '耐心',     '耐心',     'nai4xin1',         'nàixīn',        'to be patient'),
    (4, '难道',     '難道',     'nan2dao4',         'nándào',        'could it be that ...?; don''t tell me ...'),
    (4, '难受',     '難受',     'nan2shou4',        'nánshòu',       'feel unwell; to suffer pain'),
    (4, '内',       '內',       'nei4',             'nèi',           'inside; inner; internal; within'),
    (4, '内容',     '內容',     'nei4rong2',        'nèiróng',       'content; substance; details'),
    (4, '能力',     '能力',     'neng2li4',         'nénglì',        'capability; capable; ability'),
    (4, '年龄',     '年齡',     'nian2ling2',       'niánlíng',      '(a person''s) age'),
    (4, '弄',       '弄',       'nong4',            'nòng',          'do; manage; to handle; make'),
    (4, '暖和',     '暖和',     'nuan3huo',         'nuǎnhuo',       'warm; nice and warm'),
    (4, '偶尔',     '偶爾',     'ou3er3',          'ǒuěr',         'occasionally; once in a while; sometimes'),
    (4, '排队',     '排隊',     'pai2 dui4',        'pái duì',       'queue; stand in line'),
    (4, '排列',     '排列',     'pai2lie4',         'páiliè',        'arrange; align; permutation'),
    (4, '判断',     '判斷',     'pan4duan4',        'pànduàn',       'to judge; judgment; to decide'),
    (4, '陪',       '陪',       'pei2',             'péi',           'accompany; keep company'),
    (4, '批评',     '批評',     'pi1ping2',         'pīpíng',        'criticize'),
    (4, '皮肤',     '皮膚',     'pi2fu1',           'pífū',          'skin'),
    (4, '脾气',     '脾氣',     'pi2qi',            'píqi',          'temperament; disposition; temper'),
    (4, '篇',       '篇',       'pian1',            'piān',          'sheet; (mw for articles); piece of writing'),
    (4, '骗',       '騙',       'pian4',            'piàn',          'to cheat; to swindle; deceive'),
    (4, '乒乓球',   '乒乓球',   'ping1pang1qiu2',   'pīngpāngqiú',   'ping pong; table tennis'),
    (4, '平时',     '平時',     'ping2shi2',        'píngshí',       'ordinarily; in normal times; in peacetime'),
    (4, '破',       '破',       'po4',              'pò',            'broken; damaged; to split'),
    (4, '葡萄',     '葡萄',     'pu2tao',           'pútao',         'grape'),
    (4, '普遍',     '普遍',     'pu3bian4',         'pǔbiàn',        'common; universal; general; widespread'),
    (4, '普通话',   '普通話',   'pu3tong1hua4',     'pǔtōnghuà',     'Mandarin (common language)'),
    (4, '其次',     '其次',     'qi2ci4',           'qícì',          'next; secondly'),
    (4, '其中',     '其中',     'qi2zhong1',        'qízhōng',       'among; in; included among these'),
    (4, '气候',     '氣候',     'qi4hou4',          'qìhòu',         'climate; atmosphere; weather'),
    (4, '千万',     '千萬',     'qian1wan4',        'qiānwàn',       'ten million; be sure to; must'),
    (4, '签证',     '簽證',     'qian1zheng4',      'qiānzhèng',     'visa'),
    (4, '敲',       '敲',       'qiao1',            'qiāo',          'knock; blackmail'),
    (4, '桥',       '橋',       'qiao2',            'qiáo',          'bridge'),
    (4, '巧克力',   '巧克力',   'qiao3ke4li4',      'qiǎokèlì',      'chocolate'),
    (4, '亲戚',     '親戚',     'qin1qi',           'qīnqi',         'a relative (i.e. family relation)'),
    (4, '轻',       '輕',       'qing1',            'qīng',          'light; easy; gentle; soft'),
    (4, '轻松',     '輕松',     'qing1song1',       'qīngsōng',      'relaxed; gentle; easygoing'),
    (4, '情况',     '情況',     'qing2kuang4',      'qíngkuàng',     'circumstance; state of affairs; situation'),
    (4, '穷',       '窮',       'qiong2',           'qióng',         'poor; exhausted'),
    (4, '区别',     '區別',     'qu1bie2',          'qūbié',         'difference; distinguish'),
    (4, '取',       '取',       'qu3',              'qǔ',            'to take; get; choose'),
    (4, '全部',     '全部',     'quan2bu4',         'quánbù',        'whole; entire; complete'),
    (4, '缺点',     '缺點',     'que1dian3',        'quēdiǎn',       'weak point; defect; fault; shortcoming'),
    (4, '缺少',     '缺少',     'que1shao3',        'quēshǎo',       'to lack; be short of; be deficient in'),
    (4, '却',       '卻',       'que4',             'què',           'but; yet; however'),
    (4, '确实',     '確實',     'que4shi2',         'quèshí',        'indeed; in truth; reliable'),
    (4, '然而',     '然而',     'ran2er2',         'ránér',        'however; yet; but'),
    (4, '热闹',     '熱鬧',     'ren4ao',           'rènao',         'bustling; lively; busy'),
    (4, '任何',     '任何',     'ren4he2',          'rènhé',         'any; whatever; whichever'),
    (4, '任务',     '任務',     'ren4wu',           'rènwu',         'a mission; an assignment; a task'),
    (4, '扔',       '扔',       'reng1',            'rēng',          'to throw; throw away'),
    (4, '仍然',     '仍然',     'reng2ran2',        'réngrán',       'still; yet'),
    (4, '日记',     '日記',     'ri4ji4',           'rìjì',          'diary'),
    (4, '入口',     '入口',     'ru4kou3',          'rùkǒu',         'entrance'),
    (4, '散步',     '散步',     'san4 bu4',         'sàn bù',        'to go for a walk'),
    (4, '森林',     '森林',     'sen1lin2',         'sēnlín',        'forest'),
    (4, '沙发',     '沙發',     'sha1fa1',          'shāfā',         'sofa'),
    (4, '伤心',     '傷心',     'shang1xin1',       'shāngxīn',      'sad; grieve; brokenhearted'),
    (4, '商量',     '商量',     'shang1liang',      'shāngliang',    'consult; talk over; discuss'),
    (4, '稍微',     '稍微',     'shao1wei1',        'shāowēi',       'a little bit; slightly'),
    (4, '勺子',     '勺子',     'shao2zi',          'sháozi',        'spoon; scoop; ladle'),
    (4, '社会',     '社會',     'she4hui4',         'shèhuì',        'society'),
    (4, '申请',     '申請',     'shen1qing3',       'shēnqǐng',      'apply for; application'),
    (4, '深',       '深',       'shen1',            'shēn',          'deep; profound; dark (of colors)'),
    (4, '甚至',     '甚至',     'shen4zhi4',        'shènzhì',       'even (to the point of); so much so that'),
    (4, '生活',     '生活',     'sheng1huo2',       'shēnghuó',      'life; livelihood; to live'),
    (4, '生命',     '生命',     'sheng1ming4',      'shēngmìng',     'life'),
    (4, '生意',     '生意',     'sheng1yi',         'shēngyi',       'business; trade'),
    (4, '省',       '省',       'sheng3',           'shěng',         'to save; economize; omit; province'),
    (4, '剩',       '剩',       'sheng4',           'shèng',         'have as remainder; be left over; surplus'),
    (4, '失败',     '失敗',     'shi1bai4',         'shībài',        'be defeated; fail; lose'),
    (4, '失望',     '失望',     'shi1wang4',        'shīwàng',       'disappointed; lose hope'),
    (4, '师傅',     '師傅',     'shi1fu',           'shīfu',         'master; qualified worker; teacher'),
    (4, '十分',     '十分',     'shi2fen1',         'shífēn',        'very; fully; 100%'),
    (4, '实际',     '實際',     'shi2ji4',          'shíjì',         'actual; reality; practice'),
    (4, '实在',     '實在',     'shi2zai4',         'shízài',        'honest; in reality; honestly; indeed; certainly'),
    (4, '使',       '使',       'shi3',             'shǐ',           'to use; to make; to cause; enable; envoy; messenger'),
    (4, '使用',     '使用',     'shi3yong4',        'shǐyòng',       'to use; employ; apply; administer; manipulate'),
    (4, '世纪',     '世紀',     'shi4ji4',          'shìjì',         'century'),
    (4, '是否',     '是否',     'shi4fou3',         'shìfǒu',        'whether (or not); if'),
    (4, '适合',     '適合',     'shi4he2',          'shìhé',         'to suit; to fit'),
    (4, '适应',     '適應',     'shi4ying4',        'shìyìng',       'to suit; to fit; adapt'),
    (4, '收',       '收',       'shou1',            'shōu',          'receive; accept; collect; to harvest'),
    (4, '收入',     '收入',     'shou1ru4',         'shōurù',        'take in; income; revenue'),
    (4, '收拾',     '收拾',     'shou1shi',         'shōushi',       'to tidy; put in order; to repair; to settle with; punish'),
    (4, '首都',     '首都',     'shou3du1',         'shǒudū',        'capital (city)'),
    (4, '首先',     '首先',     'shou3xian1',       'shǒuxiān',      'first (of all); in the first place; firstly'),
    (4, '受不了',   '受不了',   'shou4 bu liao3',   'shòu bu liǎo',  'cannot endure; unbearable; can''t stand'),
    (4, '受到',     '受到',     'shou4dao4',        'shòudào',       'receive (influence, restriction, etc.); be subjected to'),
    (4, '售货员',   '售貨員',   'shou4huo4yuan2',   'shòuhuòyuán',   'salesclerk; shop assistant'),
    (4, '输',       '輸',       'shu1',             'shū',           'to transport; to lose (a game, etc.)'),
    (4, '熟悉',     '熟悉',     'shu2xi1',          'shúxī',         'familiar with; know well'),
    (4, '数量',     '數量',     'shu4liang4',       'shùliàng',      'amount; quantity; number'),
    (4, '数字',     '數字',     'shu4zi4',          'shùzì',         'number; numeral; figure; digit'),
    (4, '帅',       '帥',       'shuai4',           'shuài',         'handsome; graceful; commander-in-chief'),
    (4, '顺便',     '順便',     'shun4bian4',       'shùnbiàn',      'conveniently; in passing; on the way'),
    (4, '顺利',     '順利',     'shun4li4',         'shùnlì',        'go smoothly; without a hitch; successful'),
    (4, '顺序',     '順序',     'shun4xu4',         'shùnxù',        'sequence; order'),
    (4, '说明',     '說明',     'shuo1ming2',       'shuōmíng',      'explain; explanation; illustrate; to show'),
    (4, '硕士',     '碩士',     'shuo4shi4',        'shuòshì',       'Master''s degree (M.A.)'),
    (4, '死',       '死',       'si3',              'sǐ',            'to die; dead; fixed; impassible; extremely'),
    (4, '速度',     '速度',     'su4du4',           'sùdù',          'speed; rate; velocity'),
    (4, '塑料袋',   '塑料袋',   'su4liao4dai4',     'sùliàodài',     'plastic bag'),
    (4, '酸',       '酸',       'suan1',            'suān',          'sour; sore; ache'),
    (4, '随便',     '隨便',     'sui2bian4',        'suíbiàn',       'as one pleases; informal; random; casual'),
    (4, '随着',     '隨著',     'sui2zhe',          'suízhe',        'along with; in the wake of'),
    (4, '孙子',     '孫子',     'sun1zi',           'sūnzi',         'grandson; son''s son'),
    (4, '所有',     '所有',     'suo3you3',         'suǒyǒu',        'all; to have; to possess'),
    (4, '台',       '台',       'tai2',             'tái',           'platform; Taiwan (abbr.); desk; stage; typhoon; (mw for machines); (classical) you (in letters)'),
    (4, '抬',       '擡',       'tai2',             'tái',           'to lift; to raise (with both palms up); carry (together)'),
    (4, '态度',     '態度',     'tai4du',           'tàidu',         'manner; bearing; attitude'),
    (4, '谈',       '談',       'tan2',             'tán',           'to talk; to chat; discuss'),
    (4, '弹钢琴',   '彈鋼琴',   'tan2 gang1qin2',   'tán gāngqín',   'play the piano'),
    (4, '汤',       '湯',       'tang1',            'tāng',          'soup; broth'),
    (4, '糖',       '糖',       'tang2',            'táng',          'sugar; candy; sweets'),
    (4, '躺',       '躺',       'tang3',            'tǎng',          'recline; lie down (on back or side)'),
    (4, '趟',       '趟',       'tang4, tang1',     'tàng, tāng',    '(mw for trips times) | to wade'),
    (4, '讨论',     '討論',     'tao3lun4',         'tǎolùn',        'to discuss; discussion; to talk over'),
    (4, '讨厌',     '討厭',     'tao3yan4',         'tǎoyàn',        'to hate; loathe; disgusting; troublesome'),
    (4, '特点',     '特點',     'te4dian3',         'tèdiǎn',        'a characteristic; trait; feature'),
    (4, '提',       '提',       'ti2',              'tí',            'to carry; to lift; to raise (an issue)'),
    (4, '提供',     '提供',     'ti2gong1',         'tígōng',        'to supply; provide; furnish'),
    (4, '提前',     '提前',     'ti2qian2',         'tíqián',        'shift to an earlier date; bring forward; to advance'),
    (4, '提醒',     '提醒',     'ti2xing3',         'tíxǐng',        'remind; call attention to; warn of'),
    (4, '填空',     '填空',     'tian2kong4',       'tiánkòng',      'fill in the blanks; fill a vacancy'),
    (4, '条件',     '條件',     'tiao2jian4',       'tiáojiàn',      'condition; circumstances; prerequisite'),
    (4, '停',       '停',       'ting2',            'tíng',          'to stop; to halt; to park (a car)'),
    (4, '挺',       '挺',       'ting3',            'tǐng',          'straighten up; stick out; rather (good); very'),
    (4, '通过',     '通過',     'tong1guo4',        'tōngguò',       'by means of; through (a method); pass through; via'),
    (4, '通知',     '通知',     'tong1zhi1',        'tōngzhī',       'notify; to inform; notice'),
    (4, '同情',     '同情',     'tong2qing2',       'tóngqíng',      'compassion; sympathy'),
    (4, '同时',     '同時',     'tong2shi2',        'tóngshí',       'at the same time; simultaneously'),
    (4, '推',       '推',       'tui1',             'tuī',           'to push; to scrape; to decline; postpone; elect'),
    (4, '推迟',     '推遲',     'tui1chi2',         'tuīchí',        'postpone; defer'),
    (4, '脱',       '脫',       'tuo1',             'tuō',           'to shed; take off; to escape'),
    (4, '袜子',     '襪子',     'wa4zi',            'wàzi',          'socks; stockings'),
    (4, '完全',     '完全',     'wan2quan2',        'wánquán',       'complete; whole; totally'),
    (4, '网球',     '網球',     'wang3qiu2',        'wǎngqiú',       'tennis; tennis ball'),
    (4, '网站',     '網站',     'wang3zhan4',       'wǎngzhàn',      'website'),
    (4, '往往',     '往往',     'wang3wang3',       'wǎngwǎng',      'often; frequently; more often than not'),
    (4, '危险',     '危險',     'wei1xian3',        'wēixiǎn',       'danger; dangerous; perilous'),
    (4, '卫生间',   '衛生間',   'wei4sheng1jian1',  'wèishēngjiān',  'restroom; bathroom; water closet (WC)'),
    (4, '味道',     '味道',     'wei4dao',          'wèidao',        'flavor; taste'),
    (4, '温度',     '溫度',     'wen1du4',          'wēndù',         'temperature'),
    (4, '文章',     '文章',     'wen2zhang1',       'wénzhāng',      'article; essay'),
    (4, '污染',     '汙染',     'wu1ran3',          'wūrǎn',         'pollution; contamination'),
    (4, '无',       '無',       'wu2',              'wú',            'have not; without; not (Kangxi radical 71)'),
    (4, '无聊',     '無聊',     'wu2liao2',         'wúliáo',        'nonsense; bored; silly; stupid'),
    (4, '无论',     '無論',     'wu2lun4',          'wúlùn',         'no matter what; regardless of whether...'),
    (4, '误会',     '誤會',     'wu4hui4',          'wùhuì',         'to misunderstand; to mistake'),
    (4, '西红柿',   '西紅柿',   'xi1hong2shi4',     'xīhóngshì',     'tomato'),
    (4, '吸引',     '吸引',     'xi1yin3',          'xīyǐn',         'attract (interest, investment, etc.)'),
    (4, '咸',       '鹹',       'xian2',            'xián',          'salty; salted; all'),
    (4, '现金',     '現金',     'xian4jin1',        'xiànjīn',       'cash'),
    (4, '羡慕',     '羨慕',     'xian4mu4',         'xiànmù',        'to envy; admire'),
    (4, '相反',     '相反',     'xiang1fan3',       'xiāngfǎn',      'opposite; contrary'),
    (4, '相同',     '相同',     'xiang1tong2',      'xiāngtóng',     'identical; same; alike'),
    (4, '香',       '香',       'xiang1',           'xiāng',         'fragrant; savory (Kangxi radical 186)'),
    (4, '详细',     '詳細',     'xiang2xi4',        'xiángxì',       'detailed; in detail; minute'),
    (4, '响',       '響',       'xiang3',           'xiǎng',         'make a sound; to ring; echo'),
    (4, '橡皮',     '橡皮',     'xiang4pi2',        'xiàngpí',       'rubber; an eraser'),
    (4, '消息',     '消息',     'xiao1xi',          'xiāoxi',        'news; information'),
    (4, '小吃',     '小吃',     'xiao3chi1',        'xiǎochī',       'snack; refreshments'),
    (4, '小伙子',   '小夥子',   'xiao3huo3zi',      'xiǎohuǒzi',     'young man; lad; youngster'),
    (4, '小说',     '小說',     'xiao3shuo1',       'xiǎoshuō',      'novel; fiction'),
    (4, '笑话',     '笑話',     'xiao4hua',         'xiàohua',       'joke; laugh at'),
    (4, '效果',     '效果',     'xiao4guo3',        'xiàoguǒ',       'effect; result'),
    (4, '心情',     '心情',     'xin1qing2',        'xīnqíng',       'mood; state of mind'),
    (4, '辛苦',     '辛苦',     'xin1ku3',          'xīnkǔ',         'hard; exhausting; toilsome; laborious'),
    (4, '信封',     '信封',     'xin4feng1',        'xìnfēng',       'envelope'),
    (4, '信息',     '信息',     'xin4xi1',          'xìnxī',         'information; news; message'),
    (4, '信心',     '信心',     'xin4xin1',         'xìnxīn',        'confidence; faith (in sb. or sth.)'),
    (4, '兴奋',     '興奮',     'xing1fen4',        'xīngfèn',       'excitement； be excited'),
    (4, '行',       '行',       'xing2',            'xíng',          'walk; be current; do; will do; okay'),
    (4, '醒',       '醒',       'xing3',            'xǐng',          'wake up'),
    (4, '幸福',     '幸福',     'xing4fu2',         'xìngfú',        'happy; blessed; fortunate'),
    (4, '性别',     '性別',     'xing4bie2',        'xìngbié',       'gender; sex; sexual distinction'),
    (4, '性格',     '性格',     'xing4ge2',         'xìnggé',        'nature; personality; temperament'),
    (4, '修理',     '修理',     'xiu1li3',          'xiūlǐ',         'to repair; perform maintenance; to overhaul'),
    (4, '许多',     '許多',     'xu3duo1',          'xǔduō',         'many; a lot; much'),
    (4, '学期',     '學期',     'xue2qi1',          'xuéqī',         'semester; school term'),
    (4, '压力',     '壓力',     'ya1li4',           'yālì',          'pressure; stress'),
    (4, '呀',       '呀',       'ya',               'ya',            'ah; oh; (used for 啊 after words ending with a, e, i, o, or ü)'),
    (4, '牙膏',     '牙膏',     'ya2gao1',          'yágāo',         'toothpaste'),
    (4, '亚洲',     '亞洲',     'Ya4zhou1',         'Yàzhōu',        'Asia'),
    (4, '严格',     '嚴格',     'yang2e2',          'yángé',         'strict; stringent; tight'),
    (4, '严重',     '嚴重',     'yan2zhong4',       'yánzhòng',      'grave; serious; critical'),
    (4, '研究',     '研究',     'yan2jiu1',         'yánjiū',        'to study; to research'),
    (4, '盐',       '鹽',       'yan2',             'yán',           'salt'),
    (4, '眼镜',     '眼鏡',     'yan3jing4',        'yǎnjìng',       'glasses; spectacles'),
    (4, '演出',     '演出',     'yan3chu1',         'yǎnchū',        'to act (in a play); to perform; to put on a show; performance'),
    (4, '演员',     '演員',     'yan3yuan2',        'yǎnyuán',       'actor or actress; performer'),
    (4, '阳光',     '陽光',     'yang2guang1',      'yángguāng',     'sunshine; sunlight'),
    (4, '养成',     '養成',     'yang3cheng2',      'yǎngchéng',     'cultivate; acquire; to form'),
    (4, '样子',     '樣子',     'yang4zi',          'yàngzi',        'manner; air; appearance; looks'),
    (4, '邀请',     '邀請',     'yao1qing3',        'yāoqǐng',       'to invite'),
    (4, '要是',     '要是',     'yao4shi',          'yàoshi',        'if; suppose; in case'),
    (4, '钥匙',     '鑰匙',     'yao4shi',          'yàoshi',        'key'),
    (4, '也许',     '也許',     'ye3xu3',           'yěxǔ',          'perhaps; probably; maybe'),
    (4, '叶子',     '葉子',     'ye4zi',            'yèzi',          'leaves'),
    (4, '页',       '頁',       'ye4',              'yè',            'page; leaf (Kangxi radical 181)'),
    (4, '一切',     '一切',     'yi2qie4',          'yíqiè',         'all; every; everything'),
    (4, '以',       '以',       'yi3',              'yǐ',            'to use; according to; so as to; for; by'),
    (4, '以为',     '以爲',     'yi3wei2',          'yǐwéi',         'think (mistakenly); consider (that); believe'),
    (4, '艺术',     '藝術',     'yi4shu4',          'yìshù',         'art'),
    (4, '意见',     '意見',     'yi4jian4',         'yìjiàn',        'opinion; view; suggestion; complaint'),
    (4, '因此',     '因此',     'yin1ci3',          'yīncǐ',         'therefore; thus; that is why; because of this'),
    (4, '引起',     '引起',     'yin3qi3',          'yǐnqǐ',         'give rise to; lead to; to cause; arouse'),
    (4, '印象',     '印象',     'yin4xiang4',       'yìnxiàng',      'impression'),
    (4, '赢',       '贏',       'ying2',            'yíng',          'to win; to beat; to profit'),
    (4, '应聘',     '應聘',     'ying4pin4',        'yìngpìn',       'accept a job offer; to apply for a job'),
    (4, '永远',     '永遠',     'yong3yuan3',       'yǒngyuǎn',      'forever; eternal; always'),
    (4, '勇敢',     '勇敢',     'yong3gan3',        'yǒnggǎn',       'brave; courageous'),
    (4, '优点',     '優點',     'you1dian3',        'yōudiǎn',       'merit; good point; a strength; a benefit'),
    (4, '优秀',     '優秀',     'you1xiu4',         'yōuxiù',        'outstanding; excellent'),
    (4, '幽默',     '幽默',     'you1mo4',          'yōumò',         'humorous'),
    (4, '尤其',     '尤其',     'you2qi2',          'yóuqí',         'especially; particularly'),
    (4, '由',       '由',       'you2',             'yóu',           'follow; from; by; through'),
    (4, '由于',     '由于',     'you2yu2',          'yóuyú',         'due to; owing to; as a result of; thanks to'),
    (4, '邮局',     '郵局',     'you2ju2',          'yóujú',         'post office'),
    (4, '友好',     '友好',     'you3hao3',         'yǒuhǎo',        'friendly (relations); close friends'),
    (4, '友谊',     '友誼',     'you3yi4',          'yǒuyì',         'friendship; companionship'),
    (4, '有趣',     '有趣',     'you3qu4',          'yǒuqù',         'interesting; fascinating; amusing'),
    (4, '于是',     '于是',     'yu2shi4',          'yúshì',         'as a result; thus; therefore'),
    (4, '愉快',     '愉快',     'yu2kuai4',         'yúkuài',        'happy; cheerful; delightful'),
    (4, '与',       '與',       'yu3',              'yǔ',            '(formal) and; to give; together with; participate; final particle expressing doubt or surprise'),
    (4, '羽毛球',   '羽毛球',   'yu3mao2qiu2',      'yǔmáoqiú',      'badminton'),
    (4, '语法',     '語法',     'yu3fa3',           'yǔfǎ',          'grammar'),
    (4, '语言',     '語言',     'yu3yan2',          'yǔyán',         'language'),
    (4, '预习',     '預習',     'yu4xi2',           'yùxí',          '(of students) prepare a lesson before class; preview'),
    (4, '原来',     '原來',     'yuan2lai2',        'yuánlái',       'original; former; as it turns out'),
    (4, '原谅',     '原諒',     'yuan2liang4',      'yuánliàng',     'to excuse; forgive; to pardon'),
    (4, '原因',     '原因',     'yuan2yin1',        'yuányīn',       'cause; reason'),
    (4, '约会',     '約會',     'yue1hui4',         'yuēhuì',        'appointment; engagement; date'),
    (4, '阅读',     '閱讀',     'yue4du2',          'yuèdú',         'read; reading'),
    (4, '云',       '雲',       'yun2',             'yún',           'cloud; Yunnan province | say; speak'),
    (4, '允许',     '允許',     'yun3xu3',          'yǔnxǔ',         'to permit; allow'),
    (4, '杂志',     '雜志',     'za2zhi4',          'zázhì',         'magazine'),
    (4, '咱们',     '咱們',     'zan2men',          'zánmen',        'we (including the listener); us; our'),
    (4, '暂时',     '暫時',     'zan4shi2',         'zànshí',        'temporary; transient; for the moment'),
    (4, '脏',       '髒',       'zang1',            'zāng',          'filthy; dirty'),
    (4, '责任',     '責任',     'zer2en4',          'zérèn',         'responsibility; blame; duty'),
    (4, '增加',     '增加',     'zeng1jia1',        'zēngjiā',       'to increase; to raise; add'),
    (4, '占线',     '占線',     'zhan4xian4',       'zhànxiàn',      'the (phone) line is busy'),
    (4, '招聘',     '招聘',     'zhao1pin4',        'zhāopìn',       'recruitment; take job applications for a job'),
    (4, '照',       '照',       'zhao4',            'zhào',          'to shine; illuminate; according to'),
    (4, '真正',     '真正',     'zhen1zheng4',      'zhēnzhèng',     'genuine; real; true'),
    (4, '整理',     '整理',     'zheng3li3',        'zhěnglǐ',       'put in order; arrange; straighten up; to tidy; to pack (luggage)'),
    (4, '正常',     '正常',     'zheng4chang2',     'zhèngcháng',    'normal; regular; ordinary'),
    (4, '正好',     '正好',     'zheng4hao3',       'zhènghǎo',      'just (in time); just right; just enough; happen to; by chance'),
    (4, '正确',     '正確',     'zheng4que4',       'zhèngquè',      'correct; proper'),
    (4, '正式',     '正式',     'zheng4shi4',       'zhèngshì',      'formal; official'),
    (4, '证明',     '證明',     'zheng4ming2',      'zhèngmíng',     'proof; testify; confirm; certificate'),
    (4, '之',       '之',       'zhi1',             'zhī',           '(literary equivalent to 的); (pronoun); of'),
    (4, '支持',     '支持',     'zhi1chi2',         'zhīchí',        'sustain; hold out; | support; stand by (e.g. international support)'),
    (4, '知识',     '知識',     'zhi1shi',          'zhīshi',        'knowledge; intellectual'),
    (4, '直接',     '直接',     'zhi2jie1',         'zhíjiē',        'direct; immediate'),
    (4, '值得',     '值得',     'zhi2de',           'zhíde',         'be worth; deserve'),
    (4, '职业',     '職業',     'zhi2ye4',          'zhíyè',         'profession; occupation'),
    (4, '植物',     '植物',     'zhi2wu4',          'zhíwù',         'plant; botanical; vegetation'),
    (4, '只好',     '只好',     'zhi3hao3',         'zhǐhǎo',        'have to; be forced to'),
    (4, '只要',     '只要',     'zhi3yao4',         'zhǐyào',        'so long as; if only; provided that'),
    (4, '指',       '指',       'zhi3',             'zhǐ',           'finger; to point (at, to, out); refer to'),
    (4, '至少',     '至少',     'zhi4shao3',        'zhìshǎo',       'at least; (to say the) least'),
    (4, '质量',     '質量',     'zhi4liang4',       'zhìliàng',      'quality; mass (physics)'),
    (4, '重',       '重',       'zhong4',           'zhòng',         'heavy; serious; important'),
    (4, '重点',     '重點',     'zhong4dian3',      'zhòngdiǎn',     'emphasis; main point'),
    (4, '重视',     '重視',     'zhong4shi4',       'zhòngshì',      'to value; take seriously'),
    (4, '周围',     '周圍',     'zhou1wei2',        'zhōuwéi',       'surroundings; vicinity; environment'),
    (4, '主意',     '主意',     'zhu3yi',           'zhǔyi',         'plan; idea; decision'),
    (4, '祝贺',     '祝賀',     'zhu4he4',          'zhùhè',         'congratulate'),
    (4, '著名',     '著名',     'zhu4ming2',        'zhùmíng',       'famous; well-known; celebration'),
    (4, '专门',     '專門',     'zhuan1men2',       'zhuānmén',      'specialized'),
    (4, '专业',     '專業',     'zhuan1ye4',        'zhuānyè',       'profession; specialized field of study; major'),
    (4, '转',       '轉',       'zhuan3, zhuan4',   'zhuǎn, zhuàn',  'to turn; to change; pass on | revolve; rotate'),
    (4, '赚',       '賺',       'zhuan4',           'zhuàn',         'earn; make a profit'),
    (4, '准确',     '准確',     'zhun3que4',        'zhǔnquè',       'accurate; precise'),
    (4, '准时',     '准時',     'zhun3shi2',        'zhǔnshí',       'punctually; on time'),
    (4, '仔细',     '仔細',     'zi3xi4',           'zǐxì',          'careful; attentive; cautious'),
    (4, '自然',     '自然',     'zi4ran2',          'zìrán',         'nature; natural'),
    (4, '自信',     '自信',     'zi4xin4',          'zìxìn',         'self-confidence'),
    (4, '总结',     '總結',     'zong3jie2',        'zǒngjié',       'summarize; conclude'),
    (4, '租',       '租',       'zu1',              'zū',            'to rent'),
    (4, '最好',     '最好',     'zui4hao3',         'zuìhǎo',        'the best; had better ...; it would be best'),
    (4, '尊重',     '尊重',     'zun1zhong4',       'zūnzhòng',      'esteem; to respect; to value; to honor'),
    (4, '左右',     '左右',     'zuo3you4',         'zuǒyòu',        'about; approximate; around | left and right'),
    (4, '作家',     '作家',     'zuo4jia1',         'zuòjiā',        'author; writer'),
    (4, '作用',     '作用',     'zuo4yong4',        'zuòyòng',       'action; activity; effect'),
    (4, '作者',     '作者',     'zuo4zhe3',         'zuòzhě',        'author; writer'),
    (4, '座',       '座',       'zuo4',             'zuò',           '(mw for mountains, bridges, tall buildings, etc.); | seat; base; stand; constellation'),
    (4, '座位',     '座位',     'zuo4wei4',         'zuòwèi',        'seat; place')
;
COMMIT TRANSACTION;
